### PR TITLE
fix(remix-dev): convert config file path to file url

### PR DESCRIPTION
**Pull request by mcansh**
Closes: #

- [ ] Docs
- [ ] Tests

Testing Strategy:

### CODE REVIEW

**Review by kentcdodds — APPROVED** [review]
Thanks 👍

**Comment by kentcdodds** [comment]
Whoops, looks like the tests don't like that change 😅

**Comment by mcansh** [comment]
> Whoops, looks like the tests don't like that change 😅

need a toString, fixed it locally for a manual test run, but in an actual test it's not happy still, looking into it :)

**Comment by mcansh** [comment]
seems like there is a jest problem somewhere, the "same" (slight modifications) tests work no problem using `node:test`

**Review by chaance — APPROVED** [review]

**Review by kentcdodds — APPROVED** [review]
Thanks!

**Pull request merged**
