### PR TITLE
PNPM fix: Add missing `history` phantom dep to `@remix-run/react` package

### PR DESCRIPTION
**Pull request by eldarshamukhamedov**
## Changes

- [x] PNPM fix: Add missing `history` phantom dep to `@remix-run/react` package

## Context

The `@remix-run/react` package has a phantom dependency on the `history` package. The `@remix-run/react` package uses `history` directly [here](https://github.com/remix-run/remix/blob/main/packages/remix-react/browser.tsx#L1-L2), but it is not listed in its `package.json` file as a dependency.

While NPM and Yarn will happily resolve the `history` phantom dependency via the `react-router-dom` dependency (thanks to their filesystem-based/Node-like lookup mechanism), PNPM will not because of its caching and symlinking approach.

See more on phantom dependencies in the [RushJS docs](https://rushjs.io/pages/advanced/phantom_deps/), although this issue isn't limited to Rush and affects all PNPM monorepo/workspace setups.

Related [issue](https://github.com/remix-run/remix/issues/154) and [comment](https://github.com/remix-run/remix/issues/154#issuecomment-980815892)

### CODE REVIEW

**Review by MichaelDeBoey — APPROVED** [review]

**Comment by mjackson** [comment]
I don't think we should be importing from `history` in `@remix-run/react`, but we probably still are because the lines between `@remix-run/react` and `react-router` are still a little blurry. Let's add it with a comment above whatever we're importing from `history` with a note that we eventually don't want to import anything directly from there in `@remix-run/react`.

**Comment by eldarshamukhamedov** [comment]
Thanks @mjackson, added `TODO` comments next to all `history` imports. Let me know if this is what you had in mind. In the future, is the intent to wrap all `history`-related functionality in `react-router`?

**Review by MichaelDeBoey — APPROVED** [review]

**Comment by derekr** [comment]
Any updates on this? I'm unable to run remix in Docker using npm workspaces. Everything works fine locally though (even build and serve). My workaround for now is installing history directly in the package that's dependent on `@remix/react`.

```
epic_swanson
www-remix:latest
EXITED (1)





> start

> remix-serve build


node:internal/modules/cjs/loader:936

  throw err;

  ^


Error: Cannot find module 'history'

Require stack:

- /app/node_modules/@remix-run/react/browser.js

- /app/node_modules/@remix-run/react/index.js

- /app/packages/www/build/index.js

- /app/node_modules/@remix-run/serve/index.js

- /app/node_modules/@remix-run/serve/cli.js

    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)

    at Function.Module._load (node:internal/modules/cjs/loader:778:27)

    at Module.require (node:internal/modules/cjs/loader:1005:19)

    at require (node:internal/modules/cjs/helpers:102:18)

    at Object.<anonymous> (/app/node_modules/@remix-run/react/browser.js:15:15)

    at Module._compile (node:internal/modules/cjs/loader:1101:14)

    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)

    at Module.load (node:internal/modules/cjs/loader:981:32)

    at Function.Module._load (node:internal/modules/cjs/loader:822:12)

    at Module.require (node:internal/modules/cjs/loader:1005:19) {

  code: 'MODULE_NOT_FOUND',

  requireStack: [

    '/app/node_modules/@remix-run/react/browser.js',

    '/app/node_modules/@remix-run/react/index.js',

    '/app/packages/www/build/index.js',

    '/app/node_modules/@remix-run/serve/index.js',

    '/app/node_modules/@remix-run/serve/cli.js'

  ]

}

npm ERR! Lifecycle script `start` failed with error: 

npm ERR! Error: command failed 

npm ERR!   in workspace: www 

npm ERR!   at location: /app/packages/www 
```

Relevant Dockerfile setup

```
FROM base AS dependencies

RUN npm ci --production && \
	cp -R node_modules /prod_node_modules && \
	cp -R packages/www/node_modules /prod_packages_www_node_modules && \
	npm i --include=dev && \
	npm cache clean --force

FROM base AS builder

COPY . /app

COPY --from=dependencies /app/node_modules /app/node_modules
COPY --from=dependencies /app/packages/www/node_modules /app/packages/www/node_modules

RUN npm run build -w www && \
	rm -rf node_modules && \
	rm -rf packages/**/node_modules
```

**Comment by eldarshamukhamedov** [comment]
@mjackson can you take another look when you get a chance?

**Pull request merged**
