### PR TITLE
chore: update `jest`-related dependencies to v28

### PR DESCRIPTION
**Pull request by penx**
Closes: Discussion at https://github.com/remix-run/remix/pull/3397#discussion_r890174749 

- [ ] Docs
- [ ] Tests

Testing Strategy:

- See if CI passes

### CODE REVIEW

**Comment by penx** [comment]
I think the failing tests are due to the following from `@remix-run/web-test`:

```json
  "exports": {
    ".": {
      "browser": "./src/lib.js",
      "require": "./dist/lib.node.cjs",
      "import": "./src/lib.node.js",
      "types": "./dist/src/lib.node.d.ts"
    },
```
https://github.com/remix-run/web-std-io/blob/f5a5e15c23247b335b8cd09d8728f957e482bc62/packages/fetch/package.json#L12

This means that Jest 28 tries to import `src/lib.js` which results in `Unexpected token 'export'`.

We can likely tell Jest to transpile this module but it should probably be fixed upstream.

@chaance ?

**Comment by penx** [comment]
Further to this, I can add the following to the jest config:

```js
  transformIgnorePatterns: [
    "/node_modules/(?!(@remix-run/web-fetch|@remix-run/web-blob|@remix-run/web-stream|@remix-run/web-form-data|@remix-run/web-file)/)",
  ],
```

But still get an error:

```sh
 FAIL   react  packages/remix-react/__tests__/transition-test.tsx
  ● Test suite failed to run

    TypeError: Class extends value undefined is not a constructor or null

      34 | class NodeRequest extends WebRequest {
      35 |   constructor(info: NodeRequestInfo, init?: NodeRequestInit) {
    > 36 |     super(info, init as RequestInit);
         |                                     ^
      37 |   }
      38 |
      39 |   public get headers(): WebHeaders {
```

This seems to relate to the types output by `@remix-run/web-fetch`:

```js
export { default, fetch, Headers, Request, Response } from "./fetch.js";
export { ReadableStream, Blob, FormData } from "./package.js";
//# sourceMappingURL=lib.node.d.ts.map
```
`node_modules/@remix-run/web-fetch/dist/src/lib.node.d.ts`

fetch.js and package.js do not exist in the distributed `@remix-run/web-fetch` and likely should be pointing to `fetch.d.ts` and `package.d.ts`

**Comment by MichaelDeBoey** [comment]
@penx Now that https://github.com/GoogleCloudPlatform/functions-framework-nodejs/pull/461 is merged, do we still need `jest` v28?

**Comment by penx** [comment]
yes, as per discussion on discord and https://github.com/remix-run/remix/issues/3402#issuecomment-1147934579

**Comment by MichaelDeBoey** [comment]
Hi @penx!

Are you still interested in getting this one merged?

If so, please rebase onto latest `dev` & resolve conflicts

Pinging @jenseng as well as I know he was looking into some Jest-related things as well

**Comment by penx** [comment]
@MichaelDeBoey sure I’ll try find some time this Wednesday to clean up this and my unrelated examples PR

**Comment by penx** [comment]
@MichaelDeBoey I've rebased, but am pretty sure this is still blocked by https://github.com/remix-run/remix/issues/3402 which I had opened https://github.com/remix-run/web-std-io/pull/11 for which was approved almost a year ago but not merged.

**Comment by jenseng** [comment]
@MichaelDeBoey thanks for the ping! I'm mostly interested in getting jest/jsdom upgraded on the react-router side, but good to see if happening here too ❤️

**Comment by MichaelDeBoey** [comment]
Closing in favor of #7220

**Pull request closed without merging**
