### PR TITLE
docs(example): Add an example to persist theme with MUI and HTTP cookie

### PR DESCRIPTION
**Pull request by arpitdalal**
Using Remix to create a persistent MUI theme switcher with HTTP cookie.

### CODE REVIEW

**Comment by kentcdodds** [comment]
Hi! We do have a Dark Mode example in the works and it's pretty extensive: #688 

If you want to make a simple MUI example that would be fine. I just think including all the dark mode/cookie stuff is duplicate work here. Would you like to simplify this?

**Review by kentcdodds — CHANGES_REQUESTED** [review]
If you'd like to simplify this, feel free :) Thanks!

I should mention we also have an emotion example as well which maybe you'd be interested in helping with :) #1485 Thank you!

**Comment by arpitdalal** [comment]
Yes, that makes sense, I wasn't aware of the dark mode example being in the works so I hacked this one together. You guys are doing an awesome job, just love Remix, haven't used web standards with React before lol. It's new and exciting!!

**Comment by kentcdodds** [comment]
Thank you for understanding! We're so happy that folks like you are willing to contribute. It makes the whole community better. Thanks for taking part!

**Pull request closed without merging**
