### PR TITLE
chore(remix-dev/cli): simplify `validateNewProjectPath` in `create` command

### PR DESCRIPTION
**Pull request by XiNiHa**
Removes a dead branch found inside the CLI code for validating project directories.

### CODE REVIEW

**Comment by MichaelDeBoey** [comment]
@XiNiHa Code changes go against `dev` branch. Please rebase your branch against latest `dev` & make sure to fix all tests.

**Comment by XiNiHa** [comment]
Not sure if I did it right or not, but tried to do what you've requested

**Comment by XiNiHa** [comment]
@MichaelDeBoey The diff is a bit confusing, but the code does the same thing (I just moved the `contents` part into the if conditions)

**Comment by MichaelDeBoey** [comment]
@XiNiHa You also removed one of the possible errors.
I think you should revert that.

**Comment by XiNiHa** [comment]
@MichaelDeBoey It was impossible to hit that error. The condition (`(await fse.pathExists(projectDir)) && (await fse.stat(projectDir)).isDirectory()`) was same for two `if`s, and the first `if` throws when `contents.length > 0`, and returned otherwise. Therefore it had no chance to hit the latter error, since the second `if` will never be visited. I believe that was intended to return on `!(contents.length > 0)` since it's safe to override the contents inside the directory in that case. I'm very sure that the code is functioning exactly same.

**Comment by MichaelDeBoey** [comment]
@XiNiHa The second one was indeed never hit, but I'm quite certain that was never @kentcdodds' intention in #2655.

Since that wasn't his intention, the `return` should move 1 line higher to get the intended code.

**Comment by XiNiHa** [comment]
@MichaelDeBoey I guess this is what you want, but I'm still not sure if it's a good idea to error when users try to create a project on an empty directory.

**Review by MichaelDeBoey — APPROVED** [review]

**Review by kentcdodds — APPROVED** [review]
Thank you!

**Pull request merged**
