### PR TITLE
wip: feat: add support for node-esm serverBuildTarget

### PR DESCRIPTION
**Pull request by jacob-ebey**
feat: add remix-esm template

### CODE REVIEW

**Comment by jacob-ebey** [comment]
https://github.com/remix-run/remix/pull/1444

**Comment by jacob-ebey** [comment]
OK, we have issues with ESM believe it or not! Mainly the "require cache" equivalent for ESM is not exposed or mutable, this means no auto reload without a memory leak the size of the bundled server module: https://ar.al/2021/02/22/cache-busting-in-node.js-dynamic-esm-imports/

I guess we have a few options here:
1.) do not attempt to make `remix dev` work for node-esm and require you to have a custom server with nodemon and use `remix watch`
2.) manage a separate process for the app instead of running it as part of the `remix dev` process. This has the main drawback of loosing any and all global state / variables you use in your app. Things like DB connections would be reset and reconnect every change in dev. This may not be a big deal but does not seem ideal to me.
3.) just send it and have a memory leak in dev. We have one today that I have not yet investigated, how much worse could it get?

**Comment by TomerAberbach** [comment]
For (2), if you wanted to avoid managing a separate process, then you could use a worker like what's mentioned in https://github.com/nodejs/modules/issues/307#issuecomment-858729422 (and kill the worker each time you want to "clear the cache")

**Comment by MichaelDeBoey** [comment]
We already did a lot of ESM-related things the last weeks, so do we still need changes from this one?

**Pull request closed without merging**
