### PR TITLE
chore(docs,examples,templates): quote glob run params in `build` command

### PR DESCRIPTION
**Pull request by CanRau**
Just ran into https://github.com/mysticatea/npm-run-all/issues/200 using Yarn 3

Quoting it "dev": "run-p 'dev:*'", like mentioned in the linked issue fixed it for me with Yarn 3 and also tested Yarn 1.22.10 and npm 8.1.0, just to make sure.

So I figured as it shouldn't break anything why not always quote it?

Ref https://github.com/mysticatea/npm-run-all/issues/200

---
As @machour  requested that I fix the conflicts in https://github.com/remix-run/remix/pull/2033 but I felt it was to much mental overhead right now to get my head around fixing the other PR 🤯  I created a new one, renaming my branch and PR and also realized that I missed `run-s` commands containing globs as well 🤦🏻‍♂️

### CODE REVIEW

**Comment by MichaelDeBoey** [comment]
@CanRau Changes to `docs`/`examples`/`templates` run against `main`.
Could you please rebase your branch onto latest `main` (and fix conflicts) & set base branch to `main` as well?

**Comment by MichaelDeBoey** [comment]
@CanRau Changes to `docs`/`examples`/`templates` run against `main`.
Could you please rebase your branch onto latest `main` (and fix conflicts) & set base branch to `main` as well?

**Comment by MichaelDeBoey** [comment]
Closing this in favor of #3595

**Comment by CanRau** [comment]
Sorry the PR/notification got lost, glad there's another one 👌

**Pull request closed without merging**
