### PR TITLE
docs(tutorials/blog): Pass `LoaderData` type as generic to `useLoaderData`

### PR DESCRIPTION
**Pull request by dca123**
Closes: #3772

- [x] Docs
- [ ] Tests

Testing Strategy:

Typescript doesn't show any errors !

### CODE REVIEW

**Comment by machour** [comment]
Thank you for your contribution!

I'm not sure if we're going to merge this PR, or we're going to wait for @MichaelDeBoey to update all docs/examples/templates to use the new loader type inference introduced in 1.6.5

**Comment by dca123** [comment]
Thanks for the reply ! 

I also noticed that `const errors = useActionData()`  in the [Actions](https://remix.run/docs/en/v1/tutorials/blog#actions) section (ctrl + f for the "Add validation messages to the UI" part) could benefit from using the `ActionData` type that we create. Should I make a new PR for this then ?

**Comment by kentcdodds** [comment]
We're going to update this to use type inference very soon. Using the generic for an explicit type is deprecated. Thanks anyway!

**Comment by jtushman** [comment]
@kentcdodds is there a simple work around for now?

**Comment by machour** [comment]
@jtushman You can do what this PR was doing, or you can adopt the new type inference as you can see in the [1.6.5 changelog entry](https://github.com/remix-run/remix/releases/tag/%40remix-run%2Fserver-runtime%401.6.5)

**Comment by jtushman** [comment]
Thats absolutely amazing -- magical!

For those following along one of my routes look like this ...


app/routes/posts/$slug.tsx
```ts
import { marked } from "marked";
import { json, LoaderArgs } from "@remix-run/node";
import { useLoaderData } from "@remix-run/react";
import { getPost } from "~/models/post.server";
import invariant from "tiny-invariant";

export const loader = async ({ params }: LoaderArgs) => {
  invariant(params.slug, `params.slug is required`)
  const post = await getPost(params.slug)
  invariant(post, `Post not found: ${params.slug}`)

  const html = marked(post.markdown)

  return json({post, html})
}

export default function PostSlug() {
  const { post, html } = useLoaderData<typeof loader>();
  return (
    <main className="mx-auto max-w-4xl">
      <h1 className="my-6 border-b-2 text-center text-3xl">
        {post.title}
      </h1>
      <div dangerouslySetInnerHTML={{ __html: html}} />
    </main>
  )
}
```

@machour -- I am happy to take a pass at making a PR to update the tutorial docs -- would that be helpful?

**Comment by machour** [comment]
@jtushman I think @MichaelDeBoey is already working on it.

**Pull request closed without merging**
