### PR TITLE
perf(remix-dev/vite): use fs watcher to invalidate manifest instead of request time

### PR DESCRIPTION
**Pull request by hi-ogawa**
Considering `resolvePluginConfig` depends only on route files and `vite.config.ts`, I think it would make sense to use file watcher to trigger invalidation instead of request time (cf. https://github.com/remix-run/remix/pull/7908).
Not in this PR yet, but I'm thinking to extend this approach to cover issues such as https://github.com/remix-run/remix/issues/7894, https://github.com/remix-run/remix/issues/8114.
If you want to tackle these issues together, then I can also continue within this PR, so please let me know.
(For now https://github.com/remix-run/remix/pull/8157/ fixes https://github.com/remix-run/remix/issues/8114 based on `handleHotUpdate`, but this logic could be moved to watcher.)

## testing strategy

Currently there's no test to exercise route file addition/removal scenario, so I added a new test `integration/vite-dev-manifest-invalidation-test.ts` to verify that the server is aware of new route file addition.
Note that client is still not aware of manifest change by itself, which is the same behavior reported in https://github.com/remix-run/remix/issues/7894.

~(Currently windows/macos CI failing. Probably I'm missing some necessary path manipulation. I will investigate this further.)~
It seems it was a slight timing issue. I "fixed" tests by using `expect.poll` to do retry for small test block.

### CODE REVIEW

**Review by markdalgleish — APPROVED** [review]
I've pushed some minor updates and refactors, but this looks good to me and makes a lot of sense. I'm happy for the other fixes to be a follow-up PR built on top of this.

**Comment by hi-ogawa** [comment]
Thanks for the review!
Now that the other PR https://github.com/remix-run/remix/pull/8157 is merged, it might be possible to move invalidation handling from `handleHotUpdate` callback to this PR's fs watcher `"change"` event, but I still have a few unknown factor about this, so I think we can postpone such further refactoring for now.

**Comment by markdalgleish** [comment]
There might be a race condition due to the fs watcher's async callback? The Vite HMR/HDR test seems to be failing intermittently now.

**Comment by hi-ogawa** [comment]
Sorry about that .That would be blocker. I'll look into it.

**Comment by hi-ogawa** [comment]
I think I found (at least one) source of flakiness, which should be fixed by https://github.com/remix-run/remix/pull/8479 (or cherry-picked commit in this PR https://github.com/remix-run/remix/pull/8164/commits/92e3f40002d55b0ab430f36fdd4450da723d0197)

Here is a quick summary:
- Flakiness was observed exclusively on Linux machine (namely both ubuntu/chromium and ubuntu/firefox) on CI.
- I use ArchLinux for dev but I couldn't reproduce it locally.
- When reading file via `fs.readFile` during `handleHotUpdate`, it sometimes ends up empty as explained in https://vitejs.dev/guide/api-plugin.html#handlehotupdate and it suggests to use `HmrContext.read` to avoid such file system io inconsistency.

This "empty" behavior is verified (though in a crude way) on CI log with this commit https://github.com/remix-run/remix/pull/8164/commits/89bfae585abf1ab2127ba720136c4c5bc1563865

https://github.com/remix-run/remix/actions/runs/7484569708/job/20371638696#step:7:463

```
## during handleHotUpdate  "sourceExports" became empty (it should at least have "default")
## and ends up with `hasLoader` flag going back to false

[getRouteMetadata:empty] routes/_index.tsx

[handleHotUpdate:invalidateVirtualModules] {
  file: '/home/runner/work/remix/remix/.tmp/integration/remix-4g4re5itv9g/app/routes/_index.tsx',
  oldRouteMetadata: {
    ...
    hasLoader: true,
    ...
  },
  newRouteMetadata: {
    ...
    hasLoader: false,
    ...
  }
}
```

Unfortunately, this "empty" issue should be fixed but there might be still a different source of flakiness (which might or might not related to this PR). For example, repeating 30 times can still hit a few errors though they are within the range of 3 retries.

https://github.com/remix-run/remix/actions/runs/7485942421/job/20375315026#step:7:159

Now I reverted back all the debugging commits and the last CI run seems comparable to current dev branch's state. Please feel free to trigger a few more CI runs to see if this change is acceptable to merge. Thanks!

(I split the change for https://github.com/remix-run/remix/pull/8479 but I'll leave the decision to your side either proceed separately or discard the other one and merge this directly)

**Review by pcattori — APPROVED** [review]

**Review by markdalgleish — COMMENTED** [review]
Thanks for following up on the test flakiness. I've merged the latest code from dev and given it a bunch of CI runs and it's looking good to me.

**Pull request merged**
