### PR TITLE
docs(route/handle): fix typo

### PR DESCRIPTION
**Pull request by humphd**
I noticed a minor issue while reading the docs for `handle`.

### CODE REVIEW

**Review by MichaelDeBoey — APPROVED** [review]

**Comment by MichaelDeBoey** [comment]
@humphd Could you please sign the CLA?
Without it, we can't merge this PR.

**Comment by humphd** [comment]
Sorry, let me fix that...

**Comment by humphd** [comment]
OK, signed and fixed (I had the wrong `contributors.yml` in my branch in previous commit, updated, sorry).

**Review by machour — APPROVED** [review]
Thanks!

**Pull request merged**
