### PR TITLE
fix(dev): remove outdated esm import warnings

### PR DESCRIPTION
**Pull request by pcattori**
Supercedes #6822

### CODE REVIEW

**Review by jacob-ebey — APPROVED** [review]

**Comment by kentcdodds** [comment]
Did this PR not make it into 1.19.2? I'm still seeing warnings with 1.19.2.

**Comment by pcattori** [comment]
@kentcdodds should have landed in 1.19.1 or 1.19.2

We removed Remix-specified warnings that produced false positives, but you might still get _actual_ warnings from `esbuild`. What do the warnings you are seeing look like?

**Comment by ngbrown** [comment]
This change didn't land in `1.19.1` or `1.19.2`. I'm not sure why the bot thought it did.

The errors shown are still the same:

```
> remix build

 info  building... (NODE_ENV=production)
 warn  esm-only package: quick-lru
┃ quick-lru is possibly an ESM-only package.
┃ To bundle it with your server, include it in `serverDependenciesToBundle`
┃ -> https://remix.run/docs/en/main/file-conventions/remix-config#serverdependenciestobundle
┗
```

**Comment by kentcdodds** [comment]
Yeah, I looked in node_modules and the code that was removed in this PR is definitely still there. 🤷‍♂️

**Comment by kentcdodds** [comment]
I just upgraded to 1.19.3 and this is *still* in there: https://unpkg.com/browse/@remix-run/dev@1.19.3/dist/compiler/server/plugins/bareImports.js (line 137)

**Pull request merged**
