### PR TITLE
docs(pages/v2): remove default values from `serverBuildTarget` section

### PR DESCRIPTION
**Pull request by MichaelDeBoey**
Follow-up of #5934

Since we're talking about replacement, I figured that we don't need to specify the default values in here in order to make it work as expected

### CODE REVIEW

**Comment by brophdawg11** [comment]
I think the default values can be helpful in this context so you know the full extent of what the old thing was doing for you.  The main docs on `remix.config.js` do include the defaults so folks can figure out if they need all these fields if they want to?

**Comment by MichaelDeBoey** [comment]
@brophdawg11 What about adding them as comments instead then?
I just don't want people to think they need to include _all_ these values in order to make it work.

**Comment by brophdawg11** [comment]
Something like this?  

```js
serverModuleFormat: "cjs", // default value, can be removed
```

@jacob-ebey what do you think?

**Comment by jacob-ebey** [comment]
@MichaelDeBoey, let's leave the values in the config but add the comment next to them for now like @brophdawg11 suggested.

**Comment by MichaelDeBoey** [comment]
@brophdawg11 @jacob-ebey I've updated this PR as requested 👍

**Review by mcansh — APPROVED** [review]

**Pull request merged**
