### PR TITLE
feat(create-remix): Add proxy support in create cli

### PR DESCRIPTION
**Pull request by freeman**
Closes: #3159 

- [ ] Docs
- [x] Tests

Testing Strategy:

I tested the built cli behind a proxy and it worked seamlessly.

### CODE REVIEW

**Comment by freeman** [comment]
slightly simplified the code by having a single agent for the whole file

**Comment by freeman** [comment]
Let me know if I should do something to get this merged.

This is adding friction to get remix adopted at work :)

**Comment by mcansh** [comment]
thanks for taking this on @freeman! i've had this on my backlog for far too long 😅. looks good to me on first glance, but i'll give it a proper review when i'm back from vacation (Monday) if it's not merged by then

**Review by mcansh — APPROVED** [review]

**Comment by freeman** [comment]
Working out the test failures

**Comment by freeman** [comment]
Issues appears only in test with `msw` because `agent-base` has a pretty fragile logic for determining the agent protocol 

https://github.com/TooTallNate/node-agent-base/blob/c011b2b8efc8de6d57600c459d49baa4c608b86b/src/index.ts#L15-L19

This logic breaks under `msw` because it overrides the normal node request processing (for good reasons !).

I saw 2 paths to fix this:
- add some logic to ensure the agent protocol is set correctly based on the target url (even if in theory this is not needed outside of the test harness)
- find a way to bypass using the agent at all if under test harness

I went with the first option as some people noted that the logic of relying on stack trace could be broken in future node versions (https://github.com/TooTallNate/node-agent-base/issues/63).

**Comment by freeman** [comment]
@mcansh could you approve the workflow run if you're ok with the changes to allow tests to pass ?

**Comment by freeman** [comment]
@mcansh I'll take a look but this seems complex to test. I'd need to spin up a temporary proxy server (this seems doable, there is a `proxy` package) and try to ensure it has been used without breaking the encapsulation...

**Comment by freeman** [comment]
@mcansh added a basic test that verifies that proxy env variable is honored.

**Pull request merged**
