### PR TITLE
Docs updates - rewording and typos

### PR DESCRIPTION
**Pull request by Gideon28**
Various minor typos, mostly around misuse of apostrophes, and a bit of rewording around the initial route link in the developer blog tutorial.

### CODE REVIEW

**Comment by Gideon28** [comment]
Awesome, I hope these changes can make their way into the docs, the rewording and highlights should hopefully make those couple of sections slightly clearer for visitors :)

**Comment by skube** [comment]
Some overlap with #612

**Review by kentcdodds — APPROVED** [review]
Superb! Thanks.

**Comment by Gideon28** [comment]
Amazing, thank you Kent! Hope to contribute something a little more significant in future 😀

**Pull request merged**
