### PR TITLE
chore: update docs links (`dev` branch)

### PR DESCRIPTION
**Pull request by MichaelDeBoey**

### CODE REVIEW

**Comment by ryanflorence** [comment]
your PRs are so delightful, thank you

**Comment by MichaelDeBoey** [comment]
@ryanflorence It's those small things that count too 😉

**Comment by ryanflorence** [comment]
Can you rebase this with `main` so the docs will update immediately (instead of in the next release).

I think you know this already but just a reminder for anybody else reading:

When making PRs

dev - source code changes
main - docs/examples

**Comment by MichaelDeBoey** [comment]
I set the base to `dev` mainly because of #1546, but I can create a separate PR for fixing `main` too if you want?

**Pull request merged**
