### PR TITLE
Update contributors.yml

### PR DESCRIPTION
**Pull request by jeremyjfleming**

### CODE REVIEW

**Comment by MichaelDeBoey** [comment]
@jeremyjfleming You should only update `contributors.yml` if you're really making a contribution.

**Comment by jeremyjfleming** [comment]
Hello Michael, 
I am trying to make a contribution to the documentation. I added my name so I can do this.

**Comment by MichaelDeBoey** [comment]
@jeremyjfleming You should do this in the same PR as your docs contribution instead of in a separate PR

**Comment by jeremyjfleming** [comment]
Alright got it. One moment

**Pull request closed without merging**
