### PR TITLE
feat(remix-server-runtime): use `type-fest`'s `Jsonify` type in `Serialize`

### PR DESCRIPTION
**Pull request by MichaelDeBoey**
- Extracted `Jsonify` so that it's easier to switch to `type-fest` at a later stage
- Added cases for positive/negative infinity, `Boolean`, `Number`, `String`, `Map` & `Set`
- Added more deep grained type for objects that have a `toJSON` function
- Update `UndefinedToOptional` type
- Renamed some generics so they're more in line with the `type-fest` codebase
  - `NonJsonPrimitive` -> `NotJsonable`
    - Also replaced `Function` with `(...arguments_: any[]) => any`
  - `SerializeTuple` -> `JsonifyList`
    - Also updated this
  - `SerializeObject` -> `JsonifyObject`
    - Also updated this

This is mainly taking over @sachinraja's awesome work from https://github.com/sindresorhus/type-fest/pull/519, thanks for that! 🙏

### CODE REVIEW

**Comment by pcattori** [comment]
@MichaelDeBoey given that we have [abandoned pretty types](https://github.com/remix-run/remix/pull/6746#issuecomment-1619068201) (at least for now), I think we are set to adopt `type-fest` types for JSON serialization

**Comment by MichaelDeBoey** [comment]
@pcattori I also applied all the changes from this repo into `type-fest`, but that does seem to break a test case ( see https://github.com/sindresorhus/type-fest/pull/638)
Any idea what would be the fix?

I'd love to get it fixed upstream & here

**Comment by pcattori** [comment]
@MichaelDeBoey left a [fix for the upstream `type-fest` PR](https://github.com/sindresorhus/type-fest/pull/638/files/6de59840c17c36c3b9cb4c2e6708acae2b33643b#r1255925547)

**Comment by MichaelDeBoey** [comment]
@pcattori I've updated this PR to the latest version of what I've done in https://github.com/sindresorhus/type-fest/pull/638 as well

**Comment by pcattori** [comment]
@MichaelDeBoey I think the goal for this PR should be to replace our types with `type-fest` entirely after the upstream PR lands, rather than just update our types to match theirs.

**Comment by MichaelDeBoey** [comment]
@pcattori Unfortunately that's not possible (yet) as `type-fest` requires Node@>=14.16, which would be a breaking change as all our packages currently require Node@>=14.0.0

`type-fest` also requires Typescript@>=4.7
As we're currently not explicit about which versions we support, I don't think this is a problem though

**Comment by MichaelDeBoey** [comment]
@pcattori It seems like there's still a problem with the `Jsonify` type 🤔
https://github.com/sindresorhus/type-fest/pull/638#issuecomment-1627802167

**Comment by pcattori** [comment]
@MichaelDeBoey since `dev` branch is now for v2 development and requires Node >=18 and TS >= 5.1, can we now switch this to just pull in the types from `type-fest`?

**Comment by MichaelDeBoey** [comment]
@pcattori I now changed this PR to use `type-fest`

**Review by pcattori — APPROVED** [review]

**Comment by smeijer** [comment]
Would it make sense to revert this PR till there is a stable solution? The `Jsonify` thing seems to be a serious issue. A lot of my loaders now return `Jsonify({})`, while they were fully typed in Remix v1.9.x.

FYI, I'm typing my loaders using the `DataFunctionArgs` type, like:

```ts
export async function loader({  }: DataFunctionArgs) {
  return defer({ obj });
}
```

**Pull request merged**
