### PR TITLE
docs(remix-eslint-config): update `README`

### PR DESCRIPTION
**Pull request by memark**
The text was outdated. The eslint-config is now added automatically by `create-remix`.

### CODE REVIEW

**Review by MichaelDeBoey — APPROVED** [review]

**Comment by memark** [comment]
>Let's get this merged! 

How? Anything more I need to do?

**Comment by MichaelDeBoey** [comment]
@memark I'm not part of the Remix team, so I can't merge PRs.

**Comment by memark** [comment]
@MichaelDeBoey Oh sorry. I incorrectly thought you were since you approved the PR.

**Review by kentcdodds — APPROVED** [review]
Thanks!

**Pull request merged**
