### PR TITLE
Add information about exporting ErrorBoundary from Resource Routes

### PR DESCRIPTION
**Pull request by kasprownik**
This information would save my team a lot of debugging after upgrading remix, so it would be great to document this for other folks.

### CODE REVIEW

**Comment by kiliman** [comment]
You may want to clarify _why_ Remix behaves this way. Resource routes are not supposed to have a UI. Whereas an `ErrorBoundary` is explicitly UI for rendering errors. I think that's why Remix transitions to a UI route.

However, technically I think this should be considered an error. If the route doesn't export a default function (the UI component) but does export other UI-related exports, then it should return a build-time error.

**Comment by kasprownik** [comment]
Thanks @kiliman, added it.

**Comment by kasprownik** [comment]
> If the route doesn't export a default function (the UI component) but does export other UI-related exports, then it should return a build-time error.

@kiliman there is a specific use case when it's valid, I provided it in this change.

**Comment by brophdawg11** [comment]
I don't think we need a whole section in the doc about `ErrorBoundary`, but instead just need to make it more explicit.  Right now the docs state:

> If a route doesn't export a default component, it can be used as a Resource Route

Could we extend that to be:

> If a route doesn't export a `default` component or an `ErrorBoundary`, it can be used as a Resource Route


If we want to include the specific error message for reference, then maybe that would be better suited as an entry in https://remix.run/docs/en/main/guides/gotchas?

**Pull request closed without merging**
