### PR TITLE
feat(remix-react): add WebSocket reconnect to `LiveReload`

### PR DESCRIPTION
**Pull request by garand**
Currently if the LiveReload socket closes, for instance if the dev server restarts, the page loses connection to the socket and needs to be manually refreshed to reconnect.

This wraps the WebSocket connection script in a function that is immediately called, and adds an `onclose` method letting the user know the connection has closed. A timeout is created (1 second) to reconnect and pass an optional config object with an `onOpen` callback to force a reload when a new connection is opened.

This was born out of my use case of building a component library outside of Remix and setting up a separate script to restart the dev server when my component library changed.

---

Original discussion on Discord.

https://discord.com/channels/770287896669978684/911308489769488485/911314308967841832

### CODE REVIEW

**Comment by machour** [comment]
Seems like this is now implemented

**Comment by garand** [comment]
@machour Are you sure? I'm not seeing this implemented yet.

**Comment by machour** [comment]
@garand you're absolutely right, got my wires mixed up 😅 
Could you fix conflicts so that the team may give this a look? Thank you, and sorry again!

**Comment by MichaelDeBoey** [comment]
@garand Please rebase your branch onto latest `dev` & fix conflicts?

**Comment by MichaelDeBoey** [comment]
@garand Could you please provide us with an update on this PR?

**Comment by garand** [comment]
Yeah, didn't have a chance to get to it yet, I'll prioritize getting it cleaned up tonight.

**Comment by garand** [comment]
@MichaelDeBoey Updated! 😅

**Review by mcansh — APPROVED** [review]
LGTM, thanks @garand!

**Comment by fknop** [comment]
Hello, I think this PR might cause issue with redirects https://github.com/remix-run/remix/issues/2997#issuecomment-1209876135

**Pull request merged**
