### PR TITLE
Add Koyeb as a deployment option

### PR DESCRIPTION
**Pull request by edouardb**
Hi there 👋 

Added Koyeb as a deployment option.

### CODE REVIEW

**Comment by sergiodxa** [comment]
Since the template doesn't come with anything different than the Remix App Server, what's the benefit of having another template? Why templates ask for the deployment target, they are actually for the adapter you want to use, any deployment service that doesn't need an special adapter would be the same as Remix App Server or Express if you want control of the server.

**Comment by edouardb** [comment]
Hi @sergiodxa 

Thanks for your reply!
I took inspiration from the Fly template which doesn’t seem to have any adapter. Did  I miss something?

**Comment by sergiodxa** [comment]
🤔 I think Fly used to require extra config and it doesn't anymore.

Anyway, I'm not a part of the team, so they would decide if they want it 💪

**Comment by edmundhung** [comment]
As an alternative, maybe we can consider making an extra options on create-remix which bootstrap with the express template.

**Comment by chaance** [comment]
Hi @edouardb, thanks for the PR! I'm not sure we are quite ready to start extending our packaged adapters just yet, but we have a new feature coming that will be very community driven and will be perfect for stuff like this. Stay tuned!

**Comment by kentcdodds** [comment]
As @chaance said, we have something even better coming soon, so I'm going to go ahead and close this PR. Stay tuned though!

**Pull request closed without merging**
