### PR TITLE
chore: enable Dependabot for GitHub Actions

### PR DESCRIPTION
**Pull request by MichaelDeBoey**
This way we don't have to update them manually anymore

### CODE REVIEW

**Review by sergiodxa — APPROVED** [review]

**Review by machour — COMMENTED** [review]
Wouldn't daily generate too much noise ?
I'd personally go with weekly

**Comment by MichaelDeBoey** [comment]
@machour It's a best practice to use major version number on GitHub Actions, so it will only be very periodically that we're getting a PR

**Review by machour — APPROVED** [review]
Oh, these are GH actions not node dependencies ☕️

**Comment by mcansh** [comment]
i really wish dependabot had grouped updates 😕

**Pull request merged**
