### PR TITLE
chore(templates): remove `description`, `license` & `name` keys from `package.json`

### PR DESCRIPTION
**Pull request by MichaelDeBoey**
As mentioned by @pcattori in https://github.com/remix-run/remix/pull/3221#discussion_r876255891, these fields aren't necessary for apps.

### CODE REVIEW

**Comment by pcattori** [comment]
`sideEffects` is actually required for bundling to work as expected. Setting `sideEffects: false` in an app's `package.json` marks all imports from that app (e.g. relative imports) as side-effect free.

**Comment by MichaelDeBoey** [comment]
@pcattori I've added `sideEffects` back to `package.json` 👍

**Comment by pcattori** [comment]
@MichaelDeBoey `name` should also be removed.

**Comment by MichaelDeBoey** [comment]
@pcattori Since each app has a certain name, I think we should keep `name` for convenience.

**Comment by pcattori** [comment]
> @pcattori Since each app has a certain name, I think we should keep `name` for convenience.

I'm not sure I follow. What convenience does the `name` provide?

**Comment by MichaelDeBoey** [comment]
If I'm not mistaken (@mcansh can probably provide more info about this), tests will also fail if examples/templates have the same/no `name` 🤔

**Comment by pcattori** [comment]
> patchup-example-names

If we already have a script for handling `name` collisions, that's a smell that `name` isn't the right thing for the job in the first place. We should instead just use the filename in the `patchup-example-names` script to populate the `name` field dynamically for the examples/tests. That would guarantee uniqueness (due to filesystem), whereas the `name` field does not prevent duplicate names.

**Comment by MichaelDeBoey** [comment]
Thinking about this a bit more and maybe we should just keep these fields, as `npm` will warn the following otherwise 🤔

```sh
npm WARN example-app No description
npm WARN example-app No repository field.
npm WARN example-app No license field.
```

**Comment by pcattori** [comment]
> Thinking about this a bit more and maybe we should just keep these fields, as `npm` will warn the following otherwise 🤔
> 
> ```shell
> npm WARN example-app No description
> npm WARN example-app No repository field.
> npm WARN example-app No license field.
> ```

Does that app have `private: true`?

**Comment by MichaelDeBoey** [comment]
> Does that app have `private: true`?

It was indeed missing that one, my bad 😅🙈

**Comment by MichaelDeBoey** [comment]
> I'm not sure I follow. What convenience does the `name` field provide?

@pcattori People are used to have a `name` in all their `package.json`s, so I think we'll get PRs to add it (again) if we decide to remove it.

`create-react-app` & `create-next-app` also add `name` to `package.json` btw.
https://github.com/facebook/create-react-app/blob/c20ccecfa1cf130a47d37908dc54959c618ce8ea/packages/create-react-app/createReactApp.js#L266-L270
https://github.com/vercel/next.js/blob/863db9b0e2a7b038348202c040f90f050fd12855/packages/create-next-app/create-app.ts#L202-L212

**Comment by mcansh** [comment]
tests won't fail without the name, we'll just get bombarded with jest haste warnings

**Comment by pcattori** [comment]
> > I'm not sure I follow. What convenience does the `name` field provide?
> 
> @pcattori People are used to have a `name` in all their `package.json`s, so I think we'll get PRs to add it (again) if we decide to remove it.
> 
> `create-react-app` & `create-next-app` also add `name` to `package.json` btw. https://github.com/facebook/create-react-app/blob/c20ccecfa1cf130a47d37908dc54959c618ce8ea/packages/create-react-app/createReactApp.js#L266-L270 https://github.com/vercel/next.js/blob/863db9b0e2a7b038348202c040f90f050fd12855/packages/create-next-app/create-app.ts#L202-L212

I don't think we'll get PRs to add it back in. People can just add their app name if they want to their app's `package.json`. We don't have an issue with that. But the template itself shouldn't include a name.

`create-react-app` and `create-next-app` also set `name` to be the _app_ name, not the _template_ name.

**Comment by MichaelDeBoey** [comment]
> They would have needed to edit it anyway if we had the template name set as the `name`, so omitting the name not any more onerous than what we currently have (the template name).

Good point!
Would it be a good idea to automatically add the app name as `name` instead?

**Comment by pcattori** [comment]
> > They would have needed to edit it anyway if we had the template name set as the `name`, so omitting the name not any more onerous than what we currently have (the template name).
> 
> Good point! Would it be a good idea to automatically add the app name as `name` instead?

I think its better to leave it out. Keeps `create-remix` simpler and makes it clear that its not required.

**Review by pcattori — APPROVED** [review]

**Pull request merged**
