### PR TITLE
chore: fix ESLint warnings

### PR DESCRIPTION
**Pull request by MichaelDeBoey**
Same as #2087, but for `dev` branch

### CODE REVIEW

**Review by LANCENET — COMMENTED** [review]
Explain

**Review by LANCENET — CHANGES_REQUESTED** [review]
Go up

**Comment by chaance** [comment]
Let's hold for now. I intentionally left some of these out of the dev updates until after the release next week, as it'll simplify merging. I'll check back on this PR then, thanks 👍

**Comment by MichaelDeBoey** [comment]
All ESLint warnings are already fixed.

`.eslintrc` changes are done in separate PRs: #2227 & #2229

**Pull request closed without merging**
