### PR TITLE
fix(docs): fix post page link href in admin page for blog tutorial

### PR DESCRIPTION
**Pull request by Hopsken**
In admin page, link href for post pages should be `/posts/${post.slug}` rather than `post.slug`

### CODE REVIEW

**Review by kentcdodds — COMMENTED** [review]
Thanks! This link is actually correct. Thanks to nested routing you don't have to construct full URLs anymore 🎉 Relative links FTW!

**Comment by Hopsken** [comment]
@kentcdodds Thanks for the reply. However, because of "Nested Routing", without the full URL, the link would be treated as `/admin/posts/${post.slug}`, which I believe is not implement.

**Comment by kentcdodds** [comment]
Gotcha! Thanks for this!

**Comment by dylancom** [comment]
@kentcdodds @Hopsken it seems this error was reintroduced again, since switching to the indie stack?
I just followed the blog tutorial and the posts inside the admin link to: "http://localhost:3000/posts/admin/my-first-post", which should be "http://localhost:3000/posts/my-first-post"

**Pull request merged**
