### PR TITLE
refactor: use ternaries rather than && in JSX

### PR DESCRIPTION
**Pull request by MichaelDeBoey**
To make @kentcdodds happy

https://kentcdodds.com/blog/use-ternaries-rather-than-and-and-in-jsx

### CODE REVIEW

**Comment by krszwsk** [comment]
Wondering if casting to a boolean and keeping the `&&` is an equally good solution 🤔

**Review by kentcdodds — APPROVED** [review]
Hee hee hee. And because I'm the docs owner I get to do this :)

**Comment by kentcdodds** [comment]
Oh rats. I just realized a few of these have highlighted lines that will be off based on this change. @MichaelDeBoey, do you think you could take a minute to check and fix any highlighted lines that broke as a result of this change?

**Comment by MichaelDeBoey** [comment]
@kentcdodds I'll look into this and create a separate PR 👍

**Pull request merged**
