### PR TITLE
[Bug]: App crash on fast browser navigation or shows wrong url

### PR DESCRIPTION
**Pull request by n8agrin**
Reproduction case for issue: https://github.com/remix-run/remix/issues/1757

To run:

```
yarn bug-report-test
```

Failure is either an error where javascript complains about `default` missing from an object, or a url not matching its content. In the case of the test, we expect `/burgers` to contain the string `cheeseburgers`, but often only gets to the first route in history, `/`

Closes: #

- [ ] Docs
- [ ] Tests

Testing Strategy:

* this is a test that reproduces the behavior in issue #1757

### CODE REVIEW

**Comment by machour** [comment]
@n8agrin this PR seems to fail at reproducing the issue. 
Also you may want to use a for loop to help readability 🙏

**Comment by n8agrin** [comment]
@machour thanks for taking a look. This fails locally for me consistently, let me try to get it failing for your ci

**Comment by n8agrin** [comment]
@machour getting this to fail on CI was tricky. I have not been able to reproduce the case where javascript throws an exception, complaining `TypeError: Cannot destructure property 'default' of 'n[e]' as it is undefined.`

The bug requires transitioning from a url that is not the remix app under test, to a url in a remix app which fails to load the correct module for the page. This is typically done either by browsing back and forth quickly, or finding a rare state, where Remix issues a 300 level http redirect to a module that has not loaded yet. This is why I've added a navigation event to `https://remix.run` itself, to ensure the test clears the remix app under test's modules from memory.

To get this to fail on CI I took a different tact, which leverages another issue I've observed locally: when this error manifests, the url does not match the page content. This seems to fail consistently on ci. That said, occasionally the flaky test retries were able to overcome the particular check, requiring I add some retries in to force the failure.

The behavior this test is trying to assert is flaky by nature. It's difficult to capture it in a succinct regression test. I recommend checking out this branch locally and running the tests for yourself. If you'd like to see the TypeError exception, follow the directions I've left in the comments and you should trivially reproduce the issue.

Also happy to jump on a call with you to explain it.

This error is blocking our production app from being able to be tested in CI, causing us and our customers real pain.
`

**Comment by machour** [comment]
Thank you so much for all the efforts trying to reproduce this issue @n8agrin.
Yes, this is definitely not easy to reproduce in CI.

I'm going to defer to @mcansh (our testing expert) or @brophdawg11 (our routing expert) on this one. 
Nothing much I can do on my side.

**Comment by n8agrin** [comment]
@machour thank you! @mcansh @brophdawg11 I've separated the failure cases into two tests. Hopefully you are able to reproduce locally and see the errors described above. Please feel free to reach out and let me know how I can help.

**Comment by n8agrin** [comment]
I still believe this is an issue. I will update the repro case against latest remix version

**Comment by brophdawg11** [comment]
I was about to re-open since this is not yet fixed but since we the issue is open, I think it's OK for this to remain closed since we can still see this reproduction when we get to addressing that bug 👍

**Comment by n8agrin** [comment]
@brophdawg11 coincidentally, yesterday I worked out a patch that fixes the underlying bug. I’ll post the diff tonight when I’m back at my keyboard

**Comment by n8agrin** [comment]
@brophdawg11 PR is here https://github.com/remix-run/remix/pull/6409 (sorry for dup msgs, covering all channels)

**Pull request closed without merging**
