### PR TITLE
feat: clean directories before initial builds

### PR DESCRIPTION
**Pull request by jacob-ebey**
Closes: #

- [ ] Docs
- [ ] Tests

### CODE REVIEW

**Comment by jacob-ebey** [comment]
> Could we put this in `buildEverything` in `compiler.ts`? That way it can be in one place and it'll get cleared between builds in watch mode as well.

`buildEverything` is actually called for re-builds as well in dev mode. We cleared out inbetween builds in the past and it caused some issues with missing assets, etc. I'd rather keep it explicit in the CLI commands layer, not compiler layer.

**Comment by jacob-ebey** [comment]
> Could we put this in `buildEverything` in `compiler.ts`? That way it can be in one place and it'll get cleared between builds in watch mode as well.

`buildEverything` is actually called for re-builds as well in dev mode. We cleared out inbetween builds in the past and it caused some issues with missing assets, etc. I'd rather keep it explicit in the CLI commands layer, not compiler layer.

**Review by kentcdodds — APPROVED** [review]
Sounds fine to me 👍 Thanks for explaining that to me.

**Comment by nicksrandall** [comment]
@kentcdodds @jacob-ebey this breaks most of the "stacks" as the "server.js" file is cleared before the server can start. IMHO, I think this change needs to be reverted until we figure out how to handle these cases.

**Comment by kentcdodds** [comment]
Thanks @nicksrandall.

Let's get this reverted.

**Pull request merged**
