### PR TITLE
chore(docs,examples,templates): update `react` & `react-dom` dependency to v18

### PR DESCRIPTION
**Pull request by MichaelDeBoey**
https://reactjs.org/blog/2022/03/29/react-v18.html

### CODE REVIEW

**Comment by jensmeindertsma** [comment]
What about the TS versions of the templates?

**Comment by MichaelDeBoey** [comment]
@jensmeindertsma They're included now

**Comment by jensmeindertsma** [comment]
Can we get the e2e tests to run on these changes? For me, all of the Cloudflare templates don't work

**Comment by kentcdodds** [comment]
We run pre-release tests when we cut a new pre-release that deploys to all our targets (for example): https://github.com/remix-run/remix/actions/runs/2059518090

These use the templates to do that, so we do have a pretty good level of confidence that things work when we publish new versions.

**Comment by MichaelDeBoey** [comment]
Putting in draft because of https://github.com/remix-run/remix/issues/2564

**Comment by creativecreature** [comment]
Hi, is this being worked on? I really want to give Remix a try and I've been eagerly waiting for the templates/tutorials to get updated!

I'm sure this is a lot of work so let me know if I could do anything to help

**Comment by MichaelDeBoey** [comment]
@creativecreature You can already do it yourself when creating a new project.
The only thing that should be needed to be updated is `dependencies` & `entry.client.tsx`:

```diff
  import { RemixBrowser } from "@remix-run/react";
- import { hydrate } from "react-dom";
+ import { hydrateRoot } from "react-dom/client";
 
- hydrate(<RemixBrowser />, document);
+ hydrateRoot(<RemixBrowser />, document);
```

**Comment by jensmeindertsma** [comment]
> @creativecreature You can already do it yourself when creating a new project. The only thing that should be needed to be updated is `dependencies` & `entry.client.tsx`:
> 
> ```diff
>   import { RemixBrowser } from "@remix-run/react";
> - import { hydrate } from "react-dom";
> + import { hydrateRoot } from "react-dom/client";
>  
> - hydrate(<RemixBrowser />, document);
> + hydrateRoot(<RemixBrowser />, document);
> ```

Should be `hydrateRoot(document, <RemixBrowser />);`

**Comment by MichaelDeBoey** [comment]
> Should be `hydrateRoot(document, <RemixBrowser />);`

Yeah my bad in the response 🙈😅

**Comment by chaance** [comment]
@MichaelDeBoey is this still active? I think we've done this everywhere already but let me know if not and I can re-open.

Also, you probably already saw but I migrated our examples to https://github.com/remix-run/examples, so even if we need to re-open we can get rid of all those changes!

**Pull request closed without merging**
