### PR TITLE
docs: add a postinstall troubleshooting docs-error in tutorials/blog.md

### LINKED ISSUE #504: [Bug]: Could not resolve `"./client"`, `"./server"`, `"./platform"`
### Which Remix packages are impacted?

- [X] `remix` (Remix core)
- [X] `create-remix`
- [ ] `@remix-run/architect`
- [ ] `@remix-run/cloudflare-workers`
- [X] `@remix-run/dev`
- [ ] `@remix-run/express`
- [ ] `@remix-run/netlify`
- [ ] `@remix-run/node`
- [X] `@remix-run/react`
- [X] `@remix-run/serve`
- [ ] `@remix-run/server-runtime`
- [ ] `@remix-run/vercel`

### What version of Remix are you using?

1.0.4

### Steps to Reproduce

Just following the very first chapter of the tutorial:

```
npx create-remix@latest [./my-remix-app, Remix App Server, TypeScript, Yes]
cd my-remix-app
npm run dev
```

<details>
<summary>
Output:
</summary>

```
~/Projects/my-remix-app via ⬢ v16.13.0
➜ npm run dev

> dev
> remix dev

Watching Remix app in development mode...

 > node_modules/remix/browser/index.js:11:14: error: Could not resolve "./client"
    11 │ export * from './client';
       ╵               ~~~~~~~~~~

  > node_modules/remix/browser/index.js:12:14: error: Could not resolve "./server"
    12 │ export * from './server';
       ╵               ~~~~~~~~~~

  > node_modules/remix/browser/index.js:13:14: error: Could not resolve "./platform"
    13 │ export * from './platform';
       ╵               ~~~~~~~~~~~~


Build failed with 3 errors:
node_modules/remix/browser/index.js:11:14: error: Could not resolve "./client"
node_modules/remix/browser/index.js:12:14: error: Could not resolve "./server"
node_modules/remix/browser/index.js:13:14: error: Could not resolve "./platform"
💿 Built in 366ms
```

</details>

<details>
<summary>
Environment details:
</summary>

```
~/Projects/my-remix-app via ⬢ v16.13.0 took 2m 53s
➜ npm -v
8.1.4

~/Projects/my-remix-app via ⬢ v16.13.0
➜ node -v
v16.13.0

~/Projects/my-remix-app via ⬢ v16.13.0
➜ sw_vers
ProductName:	macOS
ProductVersion:	12.0.1
BuildVersion:	21A559
```

</details>

### Expected Behavior

The app would start properly and become available under http://localhost:3000 as per tutorial guidelines

### Actual Behavior

The app does not start due to build failing on module resolution

### PR DESCRIPTION
**Pull request by kubaprzetakiewicz**
fixes #504, thanks to @girishk21 & @EtienneGrall

### CODE REVIEW

**Comment by kubaprzetakiewicz** [comment]
#504

**Review by MichaelDeBoey — APPROVED** [review]

**Comment by tylerbrostrom** [comment]
May be helpful to give a shout to `pnpm` here. Unlike `npm`, `pnpm` does not automatically run `post` and `pre` script hooks. https://pnpm.io/cli/run#differences-with-npm-run

**Comment by kubaprzetakiewicz** [comment]
> May be helpful to give a shout to `pnpm` here. Unlike `npm`, `pnpm` does not automatically run `post` and `pre` script hooks. https://pnpm.io/cli/run#differences-with-npm-run

thanks, updated

**Review by kentcdodds — APPROVED** [review]
Stellar. Thanks!

**Pull request merged**
