### PR TITLE
fix: Can no longer access header values sent through JSON helper via loaderHeaders.get

### LINKED ISSUE #1140: [Bug]: Can no longer access header values sent through JSON helper via `loaderHeaders.get`
### Which Remix packages are impacted?

- [X] `remix` (Remix core)
- [ ] `create-remix`
- [ ] `@remix-run/architect`
- [ ] `@remix-run/cloudflare-workers`
- [ ] `@remix-run/dev`
- [ ] `@remix-run/express`
- [ ] `@remix-run/netlify`
- [ ] `@remix-run/node`
- [ ] `@remix-run/react`
- [ ] `@remix-run/serve`
- [ ] `@remix-run/server-runtime`
- [ ] `@remix-run/vercel`

### What version of Remix are you using?

1.1.1

### What version of Node are you using? Minimum supported version is 14.

16.14.0

### Steps to Reproduce

If I try to access headers sent via the JSON HTTP helper within my exported `headers` function, the values are always null -

```
import { json } from 'remix'

export let loader: LoaderFunction = async () => {
  let data = await getData()

  return json(data, {
    headers: {
      'Cache-Control': 'max-age=300, s-maxage=300, stale-while-revalidate',
      'Some-Random-Header': 'some-random-value',
    },
  })
}

export function headers({ loaderHeaders }: { loaderHeaders: Headers }) {
  console.log(loaderHeaders.get('Cache-Control')) // null
  console.log(loaderHeaders.get('Some-Random-header')) // null
  return {
    'Cache-Control': loaderHeaders.get('Cache-Control'),
  }
}
```

### Expected Behavior

`loaderHeaders.get('Cache-Control')` value is `'max-age=300, s-maxage=300, stale-while-revalidate'`
`loaderHeaders.get('Some-Random-header')` value is `'some-random-value'`

### Actual Behavior

`loaderHeaders.get('Cache-Control')` value is `null`
`loaderHeaders.get('Some-Random-header')` value is `null`

### PR DESCRIPTION
**Pull request by himorishige**
I modified the header values sent by the JSON helper to be accessible via loaderHeaders.get

close #1140

### CODE REVIEW

**Comment by ryanflorence** [comment]
You mind writing a test for this? I'm unclear on how the bug surfaces, and why this fixes it.

I'd expect the fix to be in the `json` helper or the code that calls `headers`.

**Comment by ryanflorence** [comment]
Please see the comments on #1140

**Comment by himorishige** [comment]
Thanks for your advice.
I'm hoping that in my environment, the header will be no-store.
However, it seemed that max-age... was displayed.

`remix 1.1.3`

```typescript
import { HeadersFunction, json, LoaderFunction } from 'remix';

export const headers: HeadersFunction = ({ loaderHeaders }) => {
  const cacheControl =
    loaderHeaders.get('Cache-Control') ??
    'max-age=0, s-maxage=60, stale-while-revalidate=60';
  return {
    'Cache-Control': cacheControl,
  };
};

export const loader: LoaderFunction = async () => {
  return json(null, { headers: { 'Cache-Control': 'no-store' } });
};

**Comment by himorishige** [comment]
Thank you.
I appreciate that you can fix it.
It seems that this issue is also related to #1518.
This PR will be closed.

**Pull request closed without merging**
