### PR TITLE
fix(remix-dev): pass `devServerPort` to React

### PR DESCRIPTION
**Pull request by alishi973**
Closes: #2620 

This issue demonstrates that ``devServerPort`` on ``remix.config.js`` will not inject into react-dev-server.

Then I reviewed #1352 by @kentcdodds and found something:

In this PR, we tried to pass remix config with ``esbuild`` module to react-dev-server:

https://github.com/remix-run/remix/blob/c3c3627374ef8b3e7b4eb7f30d614eeae48b37ef/packages/remix-dev/compiler.ts#L365-L370

According to ``esbuild`` test files, it's correct, and everything should be working fine and passes the parameter.
here is ``esbuild`` test files for the ``define`` property:
https://github.com/evanw/esbuild/blob/c02c99fc74373aed6d58e7a349b463cd26e1d86f/scripts/js-api-tests.js#L3847-L3861

Also, check this test:
https://github.com/remix-run/remix/blob/c3c3627374ef8b3e7b4eb7f30d614eeae48b37ef/packages/remix-react/__tests__/components-test.tsx#L48-L54
 
On line 49 we assign ``devServerPort`` directly to ``process.env``, so react-dev-server will pick this variable, but in a normal situation, we did not use ``process.env`` for passing variables and used ``define`` property on ``esbuild`` .

and finally, any change on this PR or suggestion about passing data from remix config to react dev server is appreciated✌️.

### CODE REVIEW

**Review by kentcdodds — COMMENTED** [review]
Thanks for this. How does the port value get to the client-side for `<LiveReload />` to work?

**Comment by alishi973** [comment]
``<LiveReload />`` component gets ``port`` as props and uses it,
But in case of ``port`` has not been declared, it will use the default parameter:
https://github.com/remix-run/remix/blob/598a244e35c0cccaf1d5d5a858dde3551a5dd71d/packages/remix-react/components.tsx#L1388-L1392
As I mentioned, we expect ``process.env.REMIX_DEV_SERVER_WS_PORT`` to have the correct value but it has an ``undefined`` value.
I tried to set this variable in the ``readConfig`` function, then we can use this variable in the ``remix-react`` without the need to pass as a parameter on ``esbuild``.

**Comment by mcansh** [comment]
my only concern is using this with Cloudflare and Deno where they don't have `process.env`, the esbuild define is _supposed_ to replace that with `config.devServerPort`, but it doesnt seem that it is happening

**Comment by alishi973** [comment]
Thanks @mcansh for your tip, I tracked everything and found why ``esbuild`` won't pass the env parameter:

We have 2 types of build:
1. Server build
2. Browser Build

For browser build everything works fine, even you can see the ``port`` that comes from the ``esbuild`` ``define`` property, for proof, you can change the ``outdir`` in ``remix-dev/compiler.ts`` on the ``createBrowserBuild`` function and see the bundle files that have correct ``port`` value.

But for Server Build, we have only one file and that bundled file has not any ``<LiveReload />`` component, this file only has ``require("@remix-run/react")``.
As far as I know, ``esbuild`` only builds (or transforms) files and can't run the file itself so for using the ``define`` property, it should exist in the source file.
But in the server builds file's content we have not used that variable, so it will be ignored.
(``esbuild`` only replace ``process.env.XXX`` with ``XXX`` value on ``define`` property and will not execute files with that parameter).

So I think we have 2 options:
1. Use global variables like ``process.env`` (and make it compatible with deno)
2. Compile ``root.tsx`` (because it uses ``<LiveReload />``) with ``esbuild`` and put it on the server build file.

**Comment by MichaelDeBoey** [comment]
Hi @alishi973!

Are you still interested in getting this one merged?

If so, please rebase onto latest `dev` & resolve conflicts/remarks

**Comment by alishi973** [comment]
Is it possible to reopen this? I’ve just been busy in recent days.
But yeah I’m interested and will resolve the issues ASAP.

**Comment by brophdawg11** [comment]
@pcattori Is this still relevant in the new v2_dev server?

**Comment by pcattori** [comment]
Obsoleted by new dev flow. With `v2_dev`, `remix dev --port` correctly sets the websocket port

**Pull request closed without merging**
