### PR TITLE
fix: multiple Flat Layout Routes

### LINKED ISSUE #1210: [Bug]: Flat Layout Routes are not working as expected
### Which Remix packages are impacted?

- [ ] `remix` (Remix core)
- [ ] `create-remix`
- [ ] `@remix-run/architect`
- [ ] `@remix-run/cloudflare-workers`
- [X] `@remix-run/dev`
- [ ] `@remix-run/express`
- [ ] `@remix-run/netlify`
- [ ] `@remix-run/node`
- [ ] `@remix-run/react`
- [ ] `@remix-run/serve`
- [ ] `@remix-run/server-runtime`
- [ ] `@remix-run/vercel`

### What version of Remix are you using?

1.1.1

### What version of Node are you using? Minimum supported version is 14.

16.13.1

### Steps to Reproduce

If we try this [Example](https://remix.run/docs/en/v1/api/conventions#flat-layout-routes) the `routesConvention.js` trow this error 

> Path undefined defined by route "routes/__app" conflicts with route "routes/__marketing"

i see this is because the routes have the same `uniqueRouteId` = '' (empty string)

I want to have multiple layouts and nested flat layouts something like this:

```
__public/
 * * home.tsx
 * * __auth/
 * * * * login.tsx
 * * * * register.tsx
__private/
 * * admin.tsx
 __public.tsx
 __private.tsx
 ```
 
 if i do this 2 things happen:

   1. Not work because the problem described up  
   2. the __auth Flat Layout its not in the routes so `login` and `register` routes are not created

### Expected Behavior

work like the example and have multiple Flat Routes inside the Flat Routes

### Actual Behavior

Error on routes

### PR DESCRIPTION
**Pull request by Weyker**
this close #1210

fullPath is allways undefined when is a Flat Layout Routes and its not necessary to mark as unique route

### CODE REVIEW

**Comment by ryanflorence** [comment]
Thanks @Weyker :)

@jacob-ebey does this look right to you?

**Comment by ryanflorence** [comment]
We need a test for this, just add two sets of pathless layout routes in the gist app and load them up.

**Comment by Weyker** [comment]
> We need a test for this, just add two sets of pathless layout routes in the gist app and load them up.

@ryanflorence it's that for me or @jacob-ebey?

**Comment by Weyker** [comment]
fixed on #1347

**Pull request closed without merging**
