### PR TITLE
fix(remix-dev): use logical or instead of nullish coalescing

### PR DESCRIPTION
**Pull request by mcansh**
it landed in [node 14](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Nullish_coalescing_operator#browser_compatibility), but I've seen it come up in discord https://canary.discord.com/channels/770287896669978684/771068344320786452/95567838904860263 and https://canary.discord.com/channels/770287896669978684/954545525984722954/956296309256646707

ah!!! the Node version check doesn't run because it explodes trying to parse before it even gets there 🤦 

Closes: #

- [ ] Docs
- [ ] Tests

### CODE REVIEW

**Comment by mcansh** [comment]
turns out latest [wrangler-action](https://github.com/cloudflare/wrangler-action/releases/tag/1.3.0) still uses node 12, but they published a `next` version with node 16, 14 hours ago (of posting this), so there's hope

**Review by sergiodxa — APPROVED** [review]

**Comment by MichaelDeBoey** [comment]
@mcansh Shouldn't the fix be to make the CLI not explode earlier then instead of what's in this PR?

**Review by jenseng — COMMENTED** [review]
see inline comment... stepping back a bit, is this change even the right way to fix it? would a better approach be to fix it earlier as @MichaelDeBoey suggests?

e.g. maybe add this to package.json
```json
"engines": {
  "node": ">=14"
}
```

**Comment by mcansh** [comment]
> 
> ```json
> 
> "engines": {
> 
>   "node": ">=14"
> 
> }
> 
> ```

that doesn't appear to prevent you from running it though, which is the reason for the runtime check

**Comment by jenseng** [comment]
Ah yeah, I think yarn might prevent the install, but not npx 🤔

**Comment by MichaelDeBoey** [comment]
@mcansh Once https://github.com/remix-run/remix/pull/2556 is merged (with the Node version check moved), I don't think we need this anymore? 🤔

**Comment by mcansh** [comment]
> @mcansh Once https://github.com/remix-run/remix/pull/2556 is merged (with the Node version check moved), I don't think we need this anymore? 🤔

yup, you're right. i also updated some things to help aid in node < 14 handling :)

**Pull request closed without merging**
