### PR TITLE
docs(gotcha): Add an entry about hydration warnings

### PR DESCRIPTION
**Pull request by machour**
Closes: #1077

- [x] Docs
- [ ] Tests

### CODE REVIEW

**Review by kentcdodds — APPROVED** [review]
Thanks!

**Comment by msakrejda** [comment]
What is this documentation actually telling us? To always browse in incognito mode (and have our users do so)? That's obviously not a solution, so I don't understand what this is suggesting. Never mind that extensions can be enabled in incognito mode. To not uninstall extensions that cause this problem? That's impractical for developers and impossible to require of end-users.

I'd like to suggest better guidance here (I ran across this myself), but I don't feel like I understand the intent behind this note.

**Comment by machour** [comment]
@msakrejda You are making a totally fair point here. I'll look into expanding the documentation here to provide a better explanation and guidance 👍🏼

**Comment by sergiodxa-silverback** [comment]
@machour it would be better to explain what React does when that happens, because I think most people think React will fail completely, when the reality is that React will do a new render as if you didn't SSR-ed your app, instead of just attaching event listener like the normal hydration process.

**Comment by sergiodxa** [comment]
@machour it would be better to explain what React does when that happens, because I think most people think React will fail completely, when the reality is that React will do a new render as if you didn’t SSR-ed your app, instead of just attaching event listener like the normal hydration process.

**Comment by machour** [comment]
@sergiodxa a couple questions here 🙏🏼 

- is what you're saying true for both React 17 et React 18 ?
- is the warning logged in production, or is it only for dev mode ?
- when react fails at hydrating, and does the new render, will Remix call loaders / actions again, or does it already have the data in the SSR response ?

**Pull request merged**
