### PR TITLE
Docs: replace `remix` imports

### PR DESCRIPTION
**Pull request by pcattori**
Mostly syntactic/mechanical changes taking into account changes to the highlighted lines in codeblocks.

Semantic/prose changes within:
- `other-api/dev.md`
- `api/conventions.md`
- `api/remix.md` (TODO)

### CODE REVIEW

**Review by kentcdodds — APPROVED** [review]
Oh nice! Thanks for doing this! I know those line highlights thing can be super annoying, so thanks for taking the time to do that.

**Comment by aweber1** [comment]
Thanks for this! I was just trying to get started with Remix this morning and the tutorial code was throwing an error about "cannot find module 'remix'". I actually started down the path of creating a PR to fix the docs but then discovered this PR 😄 (so, another "thanks" for saving me some time)

**Review by machour — APPROVED** [review]
@pcattori awesome work, let's get this one merged rapidly 🎉

**Comment by pcattori** [comment]
Since people seem to be running into issues with the old examples/tutorials, I'll merge this now. I'll update the `api/remix.md` page in a separate PR.

**Comment by kentcdodds** [comment]
Thanks!

**Comment by MichaelDeBoey** [comment]
@pcattori This should have been merged into `main` I guess? 🤔

**Comment by kentcdodds** [comment]
Oh yeah, let's cherry pick it over

**Comment by RelatedTitle** [comment]
Shouldn't `@remix-run/server-runtime` be used instead of `@remix-run/node`?

**Comment by pcattori** [comment]
@RelatedTitle : `server-runtime` is an internal package that provides utilities for each of our concrete server runtimes (`node`, `cloudflare`, and (soon) `deno`).

You can just swap `@remix-run/node` with `@remix-run/cloudflare` in the examples/tutorials to make it work with Cloudflare (and same thing for `deno` once we add a `@remix-run/deno` package).

We need to figure out how to convey this in the docs. Will be part of the follow-on work that includes updating `api/remix.md`.

**Pull request merged**
