### PR TITLE
Add MaxAge for remix serve #903

### PR DESCRIPTION
**Pull request by ch4nd4n**
Fixes issue raised #903 by introducing ENV variable REMIX_SERVE_MAX_AGE

```bash
REMIX_SERVE_MAX_AGE=5s npm run dev
```

### CODE REVIEW

**Comment by ryanflorence** [comment]
Thanks for the catch! Let's remove the envvar and just hard code it to `1h`. If people want it to work differently they can use the express adapter.

**Comment by ch4nd4n** [comment]
@ryanflorence done.

**Comment by sheepsteak** [comment]
This doesn't quite fix #903 as all assets are still set as `immutable` like `public/favicon.ico` and `public/robots.txt` even though they're not fingerprinted. I've been using this in my Express template:

```typescript
if (mode === "production") {
  // Remix fingerprints its assets so we can cache forever
  app.use(
    "/build",
    express.static("public/build", { immutable: true, maxAge: "1y" })
  );
  // Any other assets such as favicons.
  app.use(express.static("public", { maxAge: "1h" }));
} else {
  // No caching needed
  app.use(express.static("public"));
}
```

In development there's then no caching used at all but in production the correct thing happens for the relevant type of asset. This could be put in `@remix-run/serve` and the Remix Express template as they both need to do this.

**Comment by kiliman** [comment]
@ch4nd4n Can you update your PR to match what the Express adapter uses. @jacob-ebey said he'll merge it in. https://discord.com/channels/770287896669978684/770287896669978687/934209360589103185

```ts
// You may want to be more aggressive with this caching
app.use(express.static('public', { maxAge: '1h' }))

// Remix fingerprints its assets so we can cache forever
app.use(express.static('public/build', { immutable: true, maxAge: '1y' }))
```

**Comment by sheepsteak** [comment]
> @ch4nd4n Can you update your PR to match what the Express adapter uses. @jacob-ebey said he'll merge it in. https://discord.com/channels/770287896669978684/770287896669978687/934209360589103185
> 
> ```ts
> // You may want to be more aggressive with this caching
> app.use(express.static('public', { maxAge: '1h' }))
> 
> // Remix fingerprints its assets so we can cache forever
> app.use(express.static('public/build', { immutable: true, maxAge: '1y' }))
> ```

Just wanted to state again that this still won't fix #903. The first `app.use(express.static('public', { maxAge: '1h' }))` will greedily take anything in `public` so the second `express.static('public/build', { immutable: true, maxAge: '1y' })` will never be used.

What I put in my comment above will fix this and also turn off caching for development altogether. The express template could do with this too.

**Comment by ch4nd4n** [comment]
> What I put in my comment above will fix this and also turn off caching for development altogether. The express template could do with this too.

This makes sense to me. I have updated the PR. Please check.

**Comment by ryanflorence** [comment]
Sorry, can you get it to match #1861? Apparently express will just use the first one defined here for `public/`.

**Comment by mjackson** [comment]
@ryanflorence I think this will actually work as-is, and it's a much more elegant approach than is currently being used in #1861.

He's using `app.use('/build', express.static('public/build', ...))`, which tells express to only apply that middleware to `/build` requests. And since that comes first, other requests for public assets will fall through to the following `app.use(express.static('public', ...))`.

**Comment by mjackson** [comment]
Actually just spoke w @ryanflorence about this. @ch4nd4n Can you please remove the `mode === "production"` check? We want to have the same caching behavior in dev that you get in production. If you don't want caching in dev, you can disable it in the browser devtools.

**Comment by ch4nd4n** [comment]
> Actually just spoke w @ryanflorence about this...
> 
> @ch4nd4n Can you please remove the `mode === "production"` check? 

@mjackson please see if this helps. I haven't been active due to office work.

**Comment by philip-weber** [comment]
@mjackson I am wondering if the caching simplification from PR #1994 in [line 23](https://github.com/remix-run/remix/blob/5ab4513e8859e72a5afcfb2a12efce7fb5b3853b/packages/create-remix/templates/express/server.js#L23) `app.use(express.static("public/build", ...))` is correct. Shouldn't it be `app.use(express.static('public', ...))` like in this PR?

**Comment by MichaelDeBoey** [comment]
This was implemented by #2363

**Pull request closed without merging**
