### PR TITLE
feat(remix-vercel)!: remove Vercel adapter

### PR DESCRIPTION
**Pull request by MichaelDeBoey**
Template was removed by #6784

### CODE REVIEW

**Comment by ryanflorence** [comment]
merged manually, though I probably should have run the tests first after the dev rebase 🫣

**Comment by MichaelDeBoey** [comment]
@ryanflorence I think you probably should have merged this PR via GitHub so the reference to this PR was kept in the commit message (and probably also in Changeset)

**Comment by brophdawg11** [comment]
We can just add them directly to the changeset - 002ed42c8811bb41ae396f1a8bf024cf3dbb58f4

**Comment by brophdawg11** [comment]
For future reference, the work in this PR got merged directly to `dev` - here's the commit: https://github.com/remix-run/remix/commit/a07ae1765e27758715531ec1571da8cbcfba7f0f

**Pull request closed without merging**
