### PR TITLE
chore(remix-dev): default to "just the basics"

### LINKED ISSUE #3000: Suggestion: Default installation should point to "Just the Basics" by default
### What version of Remix are you using?

1.4.1

### Steps to Reproduce

Run npx create-remix@latest

### Expected Behavior

You are asked, "What type of app do you want to create?"
The default one that is selected is the more advanced option.

It might be better for beginners to remix if the default option was "Just the Basics"

### Actual Behavior

My suggestion is for the question "What type of app do you want to create?" make the default option "Just the Basics"

### PR DESCRIPTION
**Pull request by mcansh**
resolves #3000

Signed-off-by: Logan McAnsh <logan@mcan.sh>

Testing Strategy:

I ran the build and ran `node ./build/node_modules/create-remix/cli.js`, then i ran `yarn test` to make sure they all still passed

### CODE REVIEW

**Comment by MichaelDeBoey** [comment]
Maybe we could also add the following (like we do with `install`? 
```js
default: 'template',
```

**Comment by mcansh** [comment]
> Maybe we could also add the following (like we do with `install`?
> 
> ```js
> default: 'template',
> ```

that's how i originally had it, but i think it's better to have the default at the top

**Comment by MichaelDeBoey** [comment]
@mcansh My suggestion was to have both, not one or the other.

**Review by MichaelDeBoey — APPROVED** [review]

**Review by machour — APPROVED** [review]

**Review by kentcdodds — APPROVED** [review]
Sounds good 👍

**Pull request merged**
