### PR TITLE
Use inline sourcemaps for server build

### LINKED ISSUE #367: Incorrect sourceMappingURL added to generated server bundle prevents debugging
Updated my gist with patch to use `sourcemap: 'inline'`. This solves the issue.

Here's the gist:
https://gist.github.com/kiliman/a9d7c874af03369a1d105a92560d89e9

### PR DESCRIPTION
**Pull request by zigomir**
Fixes #367

### CODE REVIEW

**Comment by jacob-ebey** [comment]
I'd actually like to make this configurable. The issue comes when deploying places like CF that have a limit on script sizes. inline source maps will almost double the files size a lot of the time.

**Comment by zigomir** [comment]
When you run `build` command, `sourcemap` is set to `false` so this shouldn't affect prod build script size.

**Comment by ryanflorence** [comment]
Thanks, we actually started on this before seeing your PR 🥲 #1087

**Comment by zigomir** [comment]
No problem :) Happy to see it landed and debugging will be nicer.

**Pull request closed without merging**
