### PR TITLE
chore: move Outlet context to React Router

### PR DESCRIPTION
**Pull request by mcansh**
dependent on https://github.com/remix-run/react-router/pull/8461 and it's release in React Router

partially reverts 64e14e95aa5c4e6aaa6a789dddb69a797d2b0369

Signed-off-by: Logan McAnsh <logan@mcan.sh>

### CODE REVIEW

**Review by kentcdodds — COMMENTED** [review]
Let's also update react-router in this PR (which we'll need to wait for).

**Review by kentcdodds — APPROVED** [review]
LGTM once the `yarn.lock` is fixed 👍

**Review by kentcdodds — CHANGES_REQUESTED** [review]
Oh, actually, we probably want to remove the tests as well.

**Comment by mcansh** [comment]
> Oh, actually, we probably want to remove the tests as well.

done!

**Pull request merged**
