### PR TITLE
feat(remix-dev): add `devServerCert` & `devServerKey` config option

### PR DESCRIPTION
**Pull request by isaacs**
Fix: https://github.com/remix-run/remix/issues/2859

Closes: #2859

- [ ] Docs
- [ ] Tests

Lacking docs and tests, provided more as a clearer sort of bug report for #2859.

### CODE REVIEW

**Comment by pascal-codetaal** [comment]
@isaacs  nice work, we can this pr :-)

**Comment by roblom** [comment]
@pascal-codetaal Merging this would be **much** appreciated! Currently hacking the command.js inside node_modules does work, but well, yeah, please? :-)

**Comment by kiliman** [comment]
@roblom Instead of hacking Remix, you can simply use the Express adapter and configure your server any way you want. I wrote a script to eject out of Remix App Server to Express.

https://github.com/kiliman/rmx-cli#eject-ras

**Comment by chaance** [comment]
I don't think this is the solution we're looking for here. We can explore better support for custom domains, but you should be able to achieve this with a custom server and a forked `<LiveReload>` component in the mean time. Looks like @kiliman has an example: https://github.com/remix-run/remix/issues/2859#issuecomment-1220057500

In the future, we'd prefer new APIs/features to be requested as a Discussion before introducing code changes in a PR. This helps us prioritize and get things on the roadmap, which makes them much more likely to land!

**Comment by isaacs** [comment]
@chaance Totally understand.

> In the future, we'd prefer new APIs/features to be requested as a Discussion before introducing code changes in a PR. This helps us prioritize and get things on the roadmap, which makes them much more likely to land!

I'll keep that in mind.  For what it's worth, in this case, I wrote a PR rather than requesting via Discussion because it was easier to express in JavaScript than in prose.  No resentment or unpleasant minutes spent on this, and my apologies if it added any friction on your end.

**Comment by kyleharper** [comment]
@chaance with your feedback here would you prefer me close my related PR too?

https://github.com/remix-run/remix/pull/4107

We can manage the patch manually for now until the dev server gets some attention.

**Comment by kyleharper** [comment]
> I don't think this is the solution we're looking for here. We can explore better support for custom domains, but you should be able to achieve this with a custom server and a forked `<LiveReload>` component in the mean time. Looks like @kiliman has an example: [#2859 (comment)](https://github.com/remix-run/remix/issues/2859#issuecomment-1220057500)
> 
> In the future, we'd prefer new APIs/features to be requested as a Discussion before introducing code changes in a PR. This helps us prioritize and get things on the roadmap, which makes them much more likely to land!

@chaance with your feedback here would you prefer me close my related [PR](https://github.com/remix-run/remix/pull/4107) too? (it attempts to solve the same issue)

My team can manage the patch manually for now until the dev server gets a new release (which I believe is in the works).

**Comment by machour** [comment]
@kyleharper I think closing the PR and going through the proposal process will be the better course of action for now 👍🏼

**Comment by chaance** [comment]
> I'll keep that in mind. For what it's worth, in this case, I wrote a PR rather than requesting via Discussion because it was easier to express in JavaScript than in prose. No resentment or unpleasant minutes spent on this, and my apologies for any added friction on your end.

No apology needed. Thanks for understanding and contributing nonetheless!

It would be great to find a way to make this work in the Remix dev server. Even nicer if we could do so without adding new config options. Environment variables could be another option to look at.

**Pull request closed without merging**
