### PR TITLE
CI test, do not merge

### PR DESCRIPTION
**Pull request by jenseng**
getting a weird GH actions failure around the yarn cache on this PR: https://github.com/remix-run/remix/pull/2027

seeing if i can repro with another commit

### CODE REVIEW

**Comment by jenseng** [comment]
✅  Confirmed, this looks like a bug in [bahmutov/npm-install](https://github.com/bahmutov/npm-install)... on Windows, installs [fail](https://github.com/remix-run/remix/runs/7081210962?check_suite_focus=true) when using `bahmutov/npm-install@v1` (i.e. `v1.8.16`) but [work](https://github.com/remix-run/remix/runs/7083386480?check_suite_focus=true) when using `bahmutov/npm-install@v1.8.15`

**Comment by MichaelDeBoey** [comment]
@jenseng Could you please file an issue on the upstream repo for this?

**Comment by jenseng** [comment]
@MichaelDeBoey yup, issue filed here: https://github.com/bahmutov/npm-install/issues/146

Also opened this Remix PR to pin the version if it's not a quick fix: https://github.com/remix-run/remix/pull/3587

**Comment by jenseng** [comment]
closing again, i have a [simpler way](https://github.com/jenseng/workflow-test/) to repro/debug :)

**Pull request closed without merging**
