### PR TITLE
fix(templates): fix version of remix packages

### PR DESCRIPTION
**Pull request by MichaelDeBoey**
Version isn't updated anymore since `templates` were moved to root of the project

---

Follow-up of #2189

CC/ @mcansh

### CODE REVIEW

**Comment by mcansh** [comment]
rats! thanks @MichaelDeBoey these should actually be "*" so they can get replaced during `create-remix`

**Comment by MichaelDeBoey** [comment]
@mcansh I'll update the `package.json`s & revert the `version` script changes then 👍

**Comment by mcansh** [comment]
> @mcansh I'll update the `package.json`s & revert the `version` script changes then 👍

perfect, thanks!

**Comment by mcansh** [comment]
aside, but the best part of these no longer being bundled is there doesn't need to be a release!

**Comment by MichaelDeBoey** [comment]
Less work for us/our scripts 🥳🎉

**Pull request merged**
