### PR TITLE
chore(templates): update `tsconfig`

### PR DESCRIPTION
**Pull request by mcansh**
recommended by typescript https://www.typescriptlang.org/tsconfig#forceConsistentCasingInFileNames

Closes: #

- [ ] Docs
- [ ] Tests

Testing Strategy:

### CODE REVIEW

**Review by MichaelDeBoey — APPROVED** [review]

**Review by MichaelDeBoey — APPROVED** [review]

**Comment by MichaelDeBoey** [comment]
@mcansh Maybe it's a good idea to do this PR against `dev`?
That way these changes will be available as soon as the next release is cut (that will include changes from #2961).

**Comment by MichaelDeBoey** [comment]
@mcansh Maybe it's a good idea to do this PR against `dev`?
That way these changes will be available as soon as the next release is cut (that will include changes from #2961).

**Comment by mcansh** [comment]
if we merge to `main` they'll be ready asap whenever someone runs `create-remix`

**Comment by mcansh** [comment]
what do you mean by "not checked against"?

**Pull request merged**
