### PR TITLE
`Form` component doesn't redirect like native component

### PR DESCRIPTION
**Pull request by kevlened**
- [ ] Docs
- [ ] Tests

Issue:

Redirecting after a native form post works successfully.

Redirecting after using Remix's `Form` component does not.

Testing Strategy:

1) I reproduced it locally
2) [I reproduced it in stack blitz](https://stackblitz.com/edit/node-ekrxhg?file=app/routes/index.tsx)
3) I wrote a test per the bug report process, but the test didn't fail

### CODE REVIEW

**Comment by machour** [comment]
Hi @kevlened 👋
We need you to sign the CLA in order for the test suite to run, could you do that?

**Comment by kevlened** [comment]
@machour done!

**Comment by machour** [comment]
@kevlened thanks! I tested the stack blitz you provided, and looking at the network tab, I see the #remix post stays pending forever with errors in the console. Can you check again locally and inspect thoroughly the network & console tabs? Something else might be going on here, like one of your extensions causing React to trip & fail.

**Comment by machour** [comment]
Update, it just completed with a `Failed to fetch` after 5 minutes 😅 My network seems to be doing fine tho.

Screen Shot 2022-08-28 at 10 32 16 PM

**Comment by kevlened** [comment]
Interesting. My local testing was in my app, but after creating a fresh remix project, I was unable to repro the behavior. I'll close this for now.

Thanks!

**Pull request closed without merging**
