### PR TITLE
feat(templates/vercel): add `$schema` in vercel config file

### PR DESCRIPTION
**Pull request by xstevenyung**
[Vercel recently added support for `$schema`](https://vercel.com/changelog/schema-autocomplete-and-validation-for-vercel-json) in the `vercel.json` to enable autocompletion and valdiation of the config file.

This PR add the `$schema` to the Vercel template.

### CODE REVIEW

**Comment by machour** [comment]
@xstevenyung The file have moved to `templates/vercel/vercel.json`, would you mind redoing your PR?

**Comment by mcansh** [comment]
> @xstevenyung The file have moved to `templates/vercel/vercel.json`, would you mind redoing your PR?

can you also update `templates/vercel-ts/vercel.json` 😄

**Comment by xstevenyung** [comment]
Updated, thanks for the heads up !

**Review by MichaelDeBoey — APPROVED** [review]

**Review by mcansh — APPROVED** [review]

**Comment by mcansh** [comment]
thanks @xstevenyung! Vercel recently introduced a "builder" so this file shouldn't be necessary anymore

**Pull request merged**
