### PR TITLE
Fix TODO header in routing guide

### PR DESCRIPTION
**Pull request by jstafman**
Minor update to the routing guide to prevent a `TODO` item from showing up in the navigation.

Closes: #

- [ ] Docs
- [ ] Tests

### CODE REVIEW

**Comment by machour** [comment]
Thank you, this have always bugged me !
Could you rebase your branch against `main`? Documentation fixes go there directly

**Comment by machour** [comment]
@jstafman go ahead and open a new PR if you want 😅

**Comment by jstafman** [comment]
@machour - Haha. I was just about to respond to tell you I don't have an enormous amount of experience contributing to open source projects, and I was having some trouble figuring out how to reconfigure this pull request to be for main instead of dev. I'll open up a new pull request. Thank you.

**Comment by jstafman** [comment]
@machour  - Please see #2381 .

**Pull request closed without merging**
