### PR TITLE
chore(remix-react): make LiveReload port required

### PR DESCRIPTION
**Pull request by mcansh**
without this change, unbundled servers wouldn't properly connect to the web socket connection

Signed-off-by: Logan McAnsh <logan@mcan.sh>

Closes: #

- [ ] Docs
- [ ] Tests

Testing Strategy:

### CODE REVIEW

**Comment by kiliman** [comment]
Ugh. Not a fan. 😒

Also, this is a breaking change for *every* Remix app out there.

**Comment by mcansh** [comment]
> Ugh. Not a fan. 😒
> 
> Also, this is a breaking change for _every_ Remix app out there.

hoping to find a better solution (which is why this is still a draft), however it will still try to use infer `process.env.REMIX_DEV_SERVER_WS_PORT` and only throw if it's still undefined

**Comment by kiliman** [comment]
I think for the most part, *remix.config* `devServerPort` is an acceptable solution. Sure, it's nice to be able to have a random port, but not at the expense of breaking code.

I have posted a workaround for random ports with multiple processes, but it required a "parent" process to get the port and set the environment variable, so it could be inherited by child processes. It definitely complicated the startup.

**Comment by mcansh** [comment]
> I think for the most part, _remix.config_ `devServerPort` is an acceptable solution. Sure, it's nice to be able to have a random port, but not at the expense of breaking code.
> 
> I have posted a workaround for random ports with multiple processes, but it required a "parent" process to get the port and set the environment variable, so it could be inherited by child processes. It definitely complicated the startup.

devServerPort sets the environment variable, which is where the issue comes in as it does set it, but the web socket is set up in the browser where the variable isn't available and then defaults to 8002 - the fact that it's random and not 8002 by default is a different bug

**Comment by kiliman** [comment]
Yes, I understand that. I even posted about it in #3314. And even included a "solution" to support random ports with environment variables for dual-process setups like Express.

All I'm saying is that everything worked fine when we simply used `devServerPort`. Granted that makes it harder to have multiple apps running, so you need to constantly update the config.

I do like the random port, and I realize that to share the port with Remix *and* the web server, you need to use an environment variable. The issue is you can't share the environment variable across sibling processes.

Perhaps `remix dev` can have a parameter that allows you to specify the process to run for the "web" server, where it defaults to `remix-serve` RAS.

`remix dev --server "node ./server.js"`. 

That way it since it is the one launching the web process, it can share environment variables across the compiler and web and everything will work properly.

Anyway, just a thought.

**Comment by kentcdodds** [comment]
I need help understanding why we have this problem in the first place.

This solution won't work. We'll need to come up with something else.

**Comment by mcansh** [comment]
> I need help understanding why we have this problem in the first place.

The issue comes down to us not bundling the `@remix-run/react` package in node targets. This leaves the reading of the port a runtime thing requiring `process.env.REMIX_XXX_PORT` var to be set on the process running the server.

```ts
<LiveReload port={Number(process.env.REMIX_DEV_SERVER_WS_PORT)} />
``` is not visually pleasing, but it does work

more info: https://discord.com/channels/770287896669978684/983424417352777728/983831766508908544

**Pull request closed without merging**
