### PR TITLE
docs(examples): ignore `routes.d.ts` and generate it automatically in `routes-gen` example

### PR DESCRIPTION
**Pull request by frontsideair**
In routes-gen example, it would be a better pattern to not commit the autogenerated route typings to the repo, instead generating them after install so they can be there for the CI.

### CODE REVIEW

**Comment by MichaelDeBoey** [comment]
@frontsideair Examples go against `main` branch.
Please rebase your branch onto `main` & set it as base branch of this PR.

**Comment by frontsideair** [comment]
Done!

**Comment by MichaelDeBoey** [comment]
@frontsideair It seems like something went wrong while rebasing.

Running the following command should fix it though:
```sh
git reset --hard main && git cherry-pick 6126f4e && git cherry-pick b5e8aea && git push -f
```

**Comment by frontsideair** [comment]
Should be fine now.

**Comment by MichaelDeBoey** [comment]
@frontsideair You still have some commits in your branch that aren't supposed to be here.
Please run

```sh
git reset --hard main && git cherry-pick 2170332 && git cherry-pick 1d2bcd3 && git cherry-pick de1290e && git push -f
```

**Comment by frontsideair** [comment]
Woah, my bad. Fixed it now, thanks!

**Review by MichaelDeBoey — APPROVED** [review]

**Pull request merged**
