### PR TITLE
fix(remix-dev/vite): preserve named exports when emptifying server/client only files

### PR DESCRIPTION
**Pull request by hi-ogawa**
Closes: https://github.com/remix-run/remix/issues/7924, https://github.com/remix-run/remix/issues/7972

Based on the idea mentioned in https://github.com/remix-run/remix/issues/7924#issuecomment-1797969780, I updated `"remix-empty-server-modules"` and `"remix-empty-client-modules"` to preserve named exports.
(It's worth noting that this won't probably fix https://github.com/remix-run/remix/issues/7957 since that issue is more related to `"remix-remove-server-exports"` plugin.)

I'm not sure if this approach is foolproof, but I thought it would be better to put together a PR to convey the idea clearly.
I would appreciate any feedback. Thanks!

## note 1

One notable (and maybe critical) difference from simple `export default {}` is that, this will now potentially expose the export names from server only files in client assets if rollup didn't tree shake named exports.
I was thinking to keep using `export default {}` for `build` case, but it turns out rollup checks export names and throws an following error, so this approach might not be robust:

<details><summary>rollup error</summary>

```
4: import serverLibDefault, { serverLibNamed } from "../server-lib.server";
...
error during build:
RollupError: "serverLibNamed" is not exported by "app/server-lib.server.tsx", imported by "app/routes/only.tsx".
```

</details>

As one more important factor to decide on this, I think it's worth noting that vite build has `minify: true` by default, so probably for most practical purposes, we can assume that original names won't be visible directly on client.
Here are the examples of client assets output with corresponding minfiy flags:

<details><summary>minify: true (default)</summary>

```js
// in build/build/assets/empty-server-client-only-a8a8a349.js
const a={};
var l={};
const o="clientLibDefault",
c=o,
u="clientLibNamed";
...
```

</details>

<details><summary>minify: false</summary>

```js
const serverLibDefault = {};
var serverLibNamed = {};
const clientLibDefault = "clientLibDefault";
const clientLibDefault$1 = clientLibDefault;
const clientLibNamed = "clientLibNamed";
...
```

</details>

## note 2

I also noticed that pre-vite remix applies "empifying" transform only for user application code, but vite version currently applies to all files including `node_modules`.

https://github.com/remix-run/remix/blob/eb2f7cbe94c04718ba9f4bd9863abd89458bde3f/packages/remix-dev/compiler/plugins/emptyModules.ts#L21-L26

I'm not sure if this change was intentional, but if it's still meant to be applied only for user code, then I think we could add additional check such as `id.startsWith(cachedPluginConfig.appDirectory)`.

### CODE REVIEW

**Comment by gustavopch** [comment]
Patching `@remix-run/dev` with these changes fixed most of the errors I was getting, but I still get this one:
```
app/monitoring.ts (38:18) "captureRemixServerException" is not exported by "node_modules/@sentry/remix/esm/index.client.js", imported by "app/monitoring.ts".
```

Context:
- I have this file `app/monitoring.ts` that exports some logging functions that are used both on the client and on the server.
- It contains `import * as Sentry from '@sentry/remix'` and it has a function that calls `Sentry.captureRemixServerException(...)` (only on the server though).
- Trying to wrap that call with `if (import.meta.env.SSR)` didn't make the error disappear.
- Using a dynamic import like `import('@sentry/remix').then(Sentry => Sentry.captureRemixServerException(...))` made the error disappear.

**Comment by hi-ogawa** [comment]
@gustavopch Thanks for testing this patch! However, I'm suspecting the issue you are seeing with `@sentry/remix` might be due to a different cause.

I tested basic setup on current remix vite (so without this PR's patch) https://stackblitz.com/edit/remix-run-remix-ikymah?file=app%2Futils.ts.

First, I can also see `vite build` (client build) showing the same message, but this is only a warning by rollup to say client build doesn't include this export. So as long as this export is not used in client code, app should be still functional. 

```
app/utils.ts (4:21) "captureRemixServerException" is not exported by "node_modules/@sentry/remix/esm/index.client.js", imported by "app/utils.ts".
```

I think what's odd is that `@sentry/remix` is swapping out `@sentry/remix` code for server and client by:

https://github.com/getsentry/sentry-javascript/blob/ff416aeb41aa729c0ed02459e8010ae3fa4016f4/packages/remix/package.json#L16-L17

```
  "module": "build/esm/index.server.js",
  "browser": "build/esm/index.client.js",
```

which itself is fine and a common thing to do, but these two modules are "incompatible" in ESM sense since these two files exports different names (e.g. client one is missing `captureRemixServerException` named export).
I think what `@sentry/remix` could do is to export `captureRemixServerException` from `index.client.js` but make its implementation to throw something like `new Error("not implemented for client")`;

**Comment by gustavopch** [comment]
@hi-ogawa Thanks for investigating and sharing the repro on StackBlitz. 🙏

I've opened an issue there: https://github.com/getsentry/sentry-javascript/issues/9594.

**Comment by pcattori** [comment]
Superceded by #8200

Specifically, we want any `.server` imports that would end up in the client bundle to cause build time failures. However, code `.client` imports often needs to be conditionally run as determined by _runtime_ checks.

**Pull request closed without merging**
