### PR TITLE
fix(remix-dev): add `@babel/preset-env` in `dependencies`

### PR DESCRIPTION
**Pull request by MichaelDeBoey**
I also took the liberty of updating all `@babel/*` deps to their latest minor

---

Fixes https://github.com/remix-run/indie-stack/issues/97

### CODE REVIEW

**Review by kentcdodds — COMMENTED** [review]
Thanks! Where do we use this plugin?

**Comment by kentcdodds** [comment]
Ah, I failed to look at the linked issue.

**Review by kentcdodds — APPROVED** [review]
Thanks!

**Comment by kentcdodds** [comment]
Hmm... Can you help me figure out why the install is failing on CI for this change?

**Comment by MichaelDeBoey** [comment]
@kentcdodds Don't know what went wrong, but a rebase seems to have fixed it

**Comment by kentcdodds** [comment]
Thanks!

**Pull request merged**
