### PR TITLE
feat!: stop passing `isTypeScript` to `remix.init` script

### PR DESCRIPTION
**Pull request by MichaelDeBoey**
Follow-up of @markdalgleish's #6887

### CODE REVIEW

**Comment by markdalgleish** [comment]
This was deliberately left in as a backwards compatibility layer for existing templates. If we do this, we might want to fast-follow the v2 release with some PRs to community templates that rely on this flag.

**Review by markdalgleish — APPROVED** [review]

**Comment by MichaelDeBoey** [comment]
@markdalgleish I'm happy to create PRs for our stacks + the official Netlify & Vercel templates (if needed)

I can also do the top 10 listed repos with [`remix-stack` tag](https://github.com/topics/remix-stack) if wanted

**Comment by brophdawg11** [comment]
IIRC we would prefer to remove remix init entirely eventually?  Is there a large benefit to removing this flag?  It sounds like it just creates a bunch more work for us (per https://github.com/remix-run/remix/pull/7099#issuecomment-1668676809) so curious if the the juice is worth the squeeze?

**Comment by MichaelDeBoey** [comment]
Imo it makes it more clear to template/stack creators that we're not supporting JS transpilation anymore so that they have to provide a JS version themselves if they want to support that

**Comment by markdalgleish** [comment]
>IIRC we would prefer to remove remix init entirely eventually? Is there a large benefit to removing this flag? It sounds like it just creates a bunch more work for us (per https://github.com/remix-run/remix/pull/7099#issuecomment-1668676809) so curious if the the juice is worth the squeeze?

I looked into removing it as part of the new `create-remix` work but found that it will take us more work to remove it than to keep it at the moment due to the way our stacks heavily rely on it. I ultimately felt that removing `remix init` would be a bunch of work (and churn for community templates) without much payoff. I'm still in favour of removing it if there's a good opportunity it in the future though.

**Comment by MichaelDeBoey** [comment]
I would say: the longer we keep it, more templates/stacks can start to rely on it, so more templates/stacks will need an update to remove it from their codebase

**Comment by brophdawg11** [comment]
I'm on board with whatever you guys think - you've got more context than I do here - just want to avoid creating any unnecessary work :).  I don't think updating the top 10 community stacks is totally necessary if we've got this clearly called out as a breaking change in v2, but if the LOE is small than it could be a nice addition.

**Comment by markdalgleish** [comment]
Yep, let's merge it.

**Pull request merged**
