### PR TITLE
chore(issue-template): Add a section about the OS/Setup/etc.

### PR DESCRIPTION
**Pull request by machour**
When doing triage, I often find myself asking about that kind of things.

I'm sure there's room for improvement, just thought I'd start this and merge your comments/ideas so that we can get all the required bits to understand the issue being reported.

### CODE REVIEW

**Review by MichaelDeBoey — COMMENTED** [review]
What do you think about separate sections with a dropdown for OS & package manager?

What do you mean by "setup" exactly?
This probably needs some clarification.

**Comment by MichaelDeBoey** [comment]
> Do you have a complete list of packages managers ?

Only ones I can think of is the ones we use as well: `npm`, `pnpm` & `yarn`
Probably a good idea to also let people tell us the version of their package manager as well.

> We definitely want a better wording here.

Some explanation or better wording would indeed help to make it clearer I think.

**Review by kentcdodds — CHANGES_REQUESTED** [review]
Thanks! If we're going to add this, let's make what we're asking for more explicit.

**Comment by machour** [comment]
Meh.

**Comment by mcansh** [comment]
we could do something like this, but add the right flags to make it not so verbose https://github.com/tabrindle/envinfo

**Pull request closed without merging**
