### PR TITLE
fix(remix-dev): apply suggested and mandatory tsconfig when values are missing

### PR DESCRIPTION
**Pull request by mcansh**
Add some tsconfig (and jsconfig) compilerOptions, some of these are required by esbuild, others are our options from our existing templates. Being that our tsconfig resolver walks the fs, i have the baseUrl resolving from that

image

Signed-off-by: Logan McAnsh <logan@mcan.sh>

### CODE REVIEW

**Review by MichaelDeBoey — APPROVED** [review]

**Comment by jacob-ebey** [comment]
Could we potentially set it to their app dir if it's not set? Or is it better to just alert about the misconfiguration?

**Comment by mcansh** [comment]
> Could we potentially set it to their app dir if it's not set? Or is it better to just alert about the misconfiguration?

for sure, I was going back on forth on it

**Comment by mcansh** [comment]
gonna implement this tomorrow, do we want to suggest/enforce any other compilerOptions? maybe the config from our templates?

**Comment by mcansh** [comment]
main goal for the PR is done, but going to also check for the required tsconfig settings for esbuild

**Comment by mcansh** [comment]
👌 
image

**Comment by mcansh** [comment]
only downside, is the build is now "slow" as it has check for these settings, I'll look at just doing the check "remix dev"

**Comment by mcansh** [comment]
actually, idk why that shows it being so slow, i'm seeing it a consistent ~520ms

**Comment by kentcdodds** [comment]
What's the watch rebuild time like? We're not rechecking every build are we? 500ms for initial boot is ok, but I wouldn't want it to be that slow for iterative builds during dev.

**Comment by mcansh** [comment]
> What's the watch rebuild time like? We're not rechecking every build are we? 500ms for initial boot is ok, but I wouldn't want it to be that slow for iterative builds during dev.

in the playground the rebuild time is almost identical, but we should be able to do a one time check

**Comment by mcansh** [comment]
added some logging to make sure things were getting recalled, and looks like the loadSync is only happening once for the initial `dev` build

**Comment by kentcdodds** [comment]
How does this impact the monorepo story?

**Comment by mcansh** [comment]
> How does this impact the monorepo story?

not a ton if any, but the original reason for the PR was that tsconfig-paths which we use for path aliases doesn't work (and doesn't tell you why) if there isn't a baseUrl set

**Comment by mcansh** [comment]
> How does this impact the monorepo story?

like any monorepo? or ours? the original reason for the PR was that tsconfig-paths which we use for path aliases doesn't work (and doesn't tell you why) if there isn't a baseUrl set

**Comment by kentcdodds** [comment]
I'm just really hesitant to auto-update someone's tsconfig for them. react-scripts does this and it's super annoying if you have a good reason for making the config the way it is. I probably don't understand the problem this is solving well enough to comfortably review/merge.

**Comment by mcansh** [comment]
totally fair, this PR started as just surfacing the missing baseUrl

**Comment by kentcdodds** [comment]
Alright. Let's go for it.

**Comment by evan-liu** [comment]
> How does this impact the monorepo story?

Hi @kentcdodds and @mcansh, this change does introduce a problem for nx monorepo where `paths` should on be extended from the top-level `tsconfig.base.json`. The change to force add `paths` to app `tsconfig` file breaks remix apps in an `nx` monorepo.

**Comment by mcansh** [comment]
@evan-liu there's a nightly linked in https://github.com/remix-run/remix/pull/2961 you can try which properly uses the extended config

**Comment by evan-liu** [comment]
I will try thanks @mcansh

**Pull request merged**
