### PR TITLE
Typo - incorrect use of quotes around the data

### PR DESCRIPTION
**Pull request by mikeybyker**
- remove quotes so the joke name is rendered

### CODE REVIEW

**Comment by machour** [comment]
Hi @mikeybyker 

The quotes aren't causing any problem (my joke name = "joke name", and it's displayed as intended):

Screen Shot 2022-08-01 at 10 00 44 AM

Have you actually had an issue running the tutorial, or were you just browsing through the documentation ?

**Comment by mikeybyker** [comment]
> Hi @mikeybyker
> 
> The quotes aren't causing any problem (my joke name = "joke name", and it's displayed as intended):
> 
> Screen Shot 2022-08-01 at 10 00 44 AM
> 
> Have you actually had an issue running the tutorial, or were you just browsing through the documentation ?

Hi - yeah just browsing sorry :-) You're right it works, but is not consistent as the individual joke page (`app/routes/jokes/$jokeId.tsx`) does not have the quotes around the joke name.

**Comment by machour** [comment]
This is a tutorial, consistency is not the goal here 😄

**Comment by mikeybyker** [comment]
> This is a tutorial, consistency of quotes is not the goal here 😄

Haha fair enough :-)

**Pull request closed without merging**
