### PR TITLE
feat(remix-dev): import `.gql` & `.graphql` files as text

### PR DESCRIPTION
**Pull request by MichaelDeBoey**
Follow-up of https://github.com/remix-run/remix/pull/3190#discussion_r873095942

### CODE REVIEW

**Comment by sergiodxa** [comment]
I think this should be as text not as file

As file will give you the path to the file, as text will give you the content as a string

I think what users will want is to get the query string as a text so it can be used directly to send a query to the API, if you get a path to a file you will have to read it, and AFAIK the path will be a URL

**Comment by MichaelDeBoey** [comment]
@sergiodxa Oops a bit too quick here 😅🙈

Should be good now

**Comment by machour** [comment]
@MichaelDeBoey shouldn't `packages/remix-dev/modules.ts` be updated too?

**Comment by MichaelDeBoey** [comment]
@machour it wasn't updated in #3190, but it should I think?

CC/ @jacob-ebey

**Comment by jacob-ebey** [comment]
> @machour it wasn't updated in #3190, but it should I think?
> 
> CC/ @jacob-ebey

Yes, it should be updated.

**Comment by MichaelDeBoey** [comment]
@jacob-ebey This should be fine to merge now

**Review by machour — APPROVED** [review]

**Pull request merged**
