### PR TITLE
docs(api/remix): fix infinite loop in `useFetcher` example

### PR DESCRIPTION
**Pull request by bjacobso**
I believe this causes an infinite loop because the fetcher is changing, this should instead be on initial mount

### CODE REVIEW

**Comment by jacob-ebey** [comment]
> Don't know if this is the right approach, as this will be against the `react-hooks/exhaustive-deps` ESLint rule
> [facebook/react#14920](https://github.com/facebook/react/issues/14920)

This is a valid use of excluding deps and one of the reasons I don't like that lint rule.

**Review by machour — APPROVED** [review]

**Comment by MichaelDeBoey** [comment]
@jacob-ebey Shouldn't we include `fetcher.load` & `fetcher.submit` into the dependencies array instead? 🤔

**Comment by bjacobso** [comment]
@MichaelDeBoey I'm still getting the lint error with `[fetcher.load]`. 

This seems to work, but looks a little clunky:
```
  const fetcherLoad = fetcher.load

  useEffect(() => {
    fetcherLoad('/example')
  }, [fetcherLoad])
```

**Comment by jonschlinkert** [comment]
Wait, isn't that an abstract example, to demonstrate the methods that can be used `useEffect`? 

In real usage, removing `fetcher` from the deps array would most likely be incorrect in almost all circumstances. You can fix the infinite loop by checking `fetcher.type` and `fetcher.state` inside `useEffect`.

**Comment by machour** [comment]
That was indeed an abstract example.
Docs have been reworked and they now include several examples avoiding the infinite loop, so I'm going to close this.
Thanks again for opening this PR @bjacobso 🙏🏼

**Comment by mbrowne** [comment]
It seems like most of the examples from the previous version of the docs have been removed. @machour were you referring to this as the recommended method?

```
  useEffect(() => {
    if (fetcher.state === "idle" && fetcher.data == null) {
      fetcher.load("/some/route");
    }
  }, [fetcher]);
```

(found at https://remix.run/docs/en/1.19.3/hooks/use-fetcher)

**Pull request closed without merging**
