### PR TITLE
templates(netlify): remove Netlify template in favor of official one

### PR DESCRIPTION
**Pull request by MichaelDeBoey**
https://github.com/netlify/remix-template

### CODE REVIEW

**Comment by brophdawg11** [comment]
Can we add a major changeset for this?

**Comment by MichaelDeBoey** [comment]
@brophdawg11 Since this is a template (not a package), we can't generate a changeset for it
We also don't have it for Vercel template btw

**Comment by brophdawg11** [comment]
We could still apply a changeset to whatever package we want though right?  This feels like something worth noting against `@remix-run/dev` where `create-remix` currently lives?  

We can also add a separate changeset for the vercel template removal and point to the original PR

**Comment by brophdawg11** [comment]
Yeah I just want to make sure that the auto-generated release notes specify that we deleted the `netlify` and `vercel` templates.  So it can go in the other changelog or a new one - doesn't really matter.  The advantage of doing it in this one is the automatic linking of the PR which did the actual deletion.

Otherwise, folks may think they can use the new `create-remix` CLI with them.  In v1, something like this would work - but it will fail in v2, so it feels like a breaking change worth noting.  Dev's don't really know/care where `create-remix` comes from

```
npx create-remix --template remix-run/remix/templates/netlify
```

**Comment by MichaelDeBoey** [comment]
@brophdawg11 I've updated https://github.com/remix-run/remix/pull/7035 already
Does that look good for you?

**Comment by brophdawg11** [comment]
I think that looks fine for Vercel.  Can we add a similar changeset as `fair-falcons-wink.md` to this PR to mention the removal of the netlify template?  It can be tagged as a major change for the netlify adatper and/or `remix-run/dev`.  I know we have it noted elsewhere, but at the moment the release notes will not say anything about the deletion of the netlify template without a changeset.

**Comment by brophdawg11** [comment]
oh - I think that was just a wrong link above, I see the changeset in https://github.com/remix-run/remix/pull/7058 👍

**Review by brophdawg11 — APPROVED** [review]

**Comment by brophdawg11** [comment]
This is good to go once conflicts are resolved 👍

**Pull request merged**
