### PR TITLE
chore(remix-dev): always minify

### PR DESCRIPTION
**Pull request by mcansh**
some folks are running into issues in dev that are solved by minification. 
also esbuild is faster when minifying

Signed-off-by: Logan McAnsh <logan@mcan.sh>

Closes: #

- [ ] Docs
- [ ] Tests

Testing Strategy:

### CODE REVIEW

**Review by jacob-ebey — APPROVED** [review]

**Comment by MichaelDeBoey** [comment]
Won't this make debugging harder in `dev` mode? 🤔

**Comment by sergiodxa** [comment]
> Won't this make debugging harder in `dev` mode as we now don't have actual function names, ... anymore? 🤔

If it generates a source map it shouldn't be an issue

**Comment by MichaelDeBoey** [comment]
> If it generates a source map it shouldn't be an issue

That's another option, but it isn't enabled by default if I'm correct.

**Review by MichaelDeBoey — APPROVED** [review]

**Comment by mjackson** [comment]
Let's not do this. There should be no need to minify in development. If there are issues that are solved with minification, we should be able to address those separately.

**Pull request closed without merging**
