### PR TITLE
fix(remix-eslint-config): add `eslint-plugin-import` as peer dependency to prevent conflicts

### PR DESCRIPTION
**Pull request by lensbart**
Closes: #4448

### CODE REVIEW

**Review by machour — CHANGES_REQUESTED** [review]
@lensbart thank you for trying to fix this!

Could you target `dev` instead of `main`? Code changes need to go there. 

Also, please have a look at the failing lint task from the CI, it seems related to your changes.

**Comment by lensbart** [comment]
Hi @machour, thanks for the quick follow-up. I changes the base branch to `dev`.

I’m a bit confused here:
* My changes (correctly) show up as just two line, 
Screenshot 2022-10-29 at 23 41 29
* But there seems to be a merge conflict,
Screenshot 2022-10-29 at 23 42 03
* which, when I click **Resolve conflicts**, shows up as follows:
Screenshot 2022-10-29 at 23 42 56

Feel free to rebase as you see fit/give me further instructions.

Regarding the CI: I currently see one failing check (remix-cla-bot Waiting for signature), but I have already contributed before, so not sure why it still asks.

Thanks!

**Comment by machour** [comment]
@MichaelDeBoey could you please do your thing here? 😅 

@lensbart once properly fixed, you'll see the errors from the CI I was mentioning!

**Review by MichaelDeBoey — COMMENTED** [review]
We're using [`@rushstack/eslint-patch`](https://github.com/microsoft/rushstack/tree/main/eslint/eslint-patch), so normally everything should work OK & we shouldn't need this update.

Both `eslint-config-airbnb` & `eslint-config-airbnb-typescript` use the latest version of `eslint-plugin-import`, just like we do, so that also shouldn't be a problem.

@lensbart Have you tried removing your `node_modules` & lockfile + installing your dependencies again freshly?

**Comment by MichaelDeBoey** [comment]
Hi @lensbart!

Are you still experiencing this problem?

I did some research & other ESLint configs (like `eslint-config-react-app`) do exactly the same thing as we do.
Maybe you should remove your package cache & try again?

**Comment by lensbart** [comment]
Hi 

> Hi @lensbart!
> 
> Are you still experiencing this problem?

Hi @MichaelDeBoey, yes, this is still a problem with v1.19.1.

When you have an `.eslintrc.js` with two overlapping `overrides` conditions (e.g., one that covers all `ts`/`tsx` files in a monorepo, and one that covers the remix app folder), running ESLint will give an error due to the latest versions of `@remix-run/eslint-config` and `` using 

> ESLint couldn't determine the plugin "react" uniquely.

and/or:

> ESLint couldn't determine the plugin "import" uniquely.

The second one is, for example, due to the latest versions of `plugin:import/recommended` and `@remix-run/eslint-config` using a different version of this plugin.

> I did some research & other ESLint configs (like `eslint-config-react-app`) do exactly the same thing as we do. Maybe you should remove your package cache & try again?

It’s not a caching issue, I tried deleting the cache.

Could you kindly reopen this?

Thanks!

**Comment by lensbart** [comment]
> I did some research & other ESLint configs (like `eslint-config-react-app`) do exactly the same thing as we do. Maybe you should remove your package cache & try again?

Based on all (sub)dependencies in use in my monorepo:

* Listing `eslint-plugin-import` as a dependency:
  - `@remix-run/eslint-config`
  - `eslint-config-react-app`
* Listing `eslint-plugin-import` as a peer dependency:
  - `eslint-config-airbnb`
  - `eslint-config-airbnb-base`
  - `eslint-config-airbnb-typescript`
  - `eslint-import-resolver-alias`
  - `eslint-import-resolver-typescript`

**Pull request closed without merging**
