### PR TITLE
fix(remix-dev): fix linked sourcemap to enabled breakpoints for debugging

### LINKED ISSUE #367: Incorrect sourceMappingURL added to generated server bundle prevents debugging
Updated my gist with patch to use `sourcemap: 'inline'`. This solves the issue.

Here's the gist:
https://gist.github.com/kiliman/a9d7c874af03369a1d105a92560d89e9

### PR DESCRIPTION
**Pull request by kiliman**
There are 2 issues with linked sourcemaps for server build:

1) sourceMappingURL uses absolute path /build
2) map file uses route: prefix in route modules so breakpoints are not found

This PR fixes both issues so sourcemap debugging works properly.

Closes #367

### CODE REVIEW

**Comment by jacob-ebey** [comment]
Do the inline once with the inclusion of "source-map-support" in @remix-run/node not work for you?

**Comment by chris-kruining** [comment]
should/could the client bundle sourcemaps get a similar treatment?

my error page is working fine with the server bundle now, but is confused about: `http://localhost:3000/build/routes/__index/cms-N234CZLH.js:6090`

It isn't superhard to reverse engineer the original callsite from this with a sourcemap lib and some clever regex. but if the client side errors could give me a stacktrace that is pointing to tsx files just like with the server bundle would be awesome and save me a bunch of work :D

to illustrate:

server error
```pre
Error: Failed to load files
    at loader4 (E:\App\Site\build\route:E:\App\Site\app\routes\__index\cms.tsx:74:15)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at Object.callRouteLoader (E:\App\Site\node_modules\@remix-run\server-runtime\data.js:73:14)
```

client error
```pre
TypeError: Cannot destructure property 'files' of 'useLoaderData(...)' as it is undefined.
    at Cms (http://localhost:3000/build/routes/__index/cms-N234CZLH.js:6090:11)
    at renderWithHooks (http://localhost:3000/build/entry.client-HEZCHDZC.js:11070:26)
    at mountIndeterminateComponent (http://localhost:3000/build/entry.client-HEZCHDZC.js:13190:21)
    at beginWork (http://localhost:3000/build/entry.client-HEZCHDZC.js:13977:22)
    at HTMLUnknownElement.callCallback2 (http://localhost:3000/build/entry.client-HEZCHDZC.js:3680:22)
    at Object.invokeGuardedCallbackDev (http://localhost:3000/build/entry.client-HEZCHDZC.js:3705:24)
    at invokeGuardedCallback (http://localhost:3000/build/entry.client-HEZCHDZC.js:3739:39)
    at beginWork$1 (http://localhost:3000/build/entry.client-HEZCHDZC.js:17086:15)
    at performUnitOfWork (http://localhost:3000/build/entry.client-HEZCHDZC.js:16314:20)
    at workLoopSync (http://localhost:3000/build/entry.client-HEZCHDZC.js:16268:13)
```

(this is in 1.2.2 btw, just saw that 1.2.3 is released, gonna update soon)

**Comment by kiliman** [comment]
@jacob-ebey Any update if this PR will be merged?

**Comment by machour** [comment]
Closes #367

**Comment by kiliman** [comment]
I've rebased my branch to latest `dev`. Any change this will be merged soon? I'm currently using `patch-package` in all my projects to enable this.

**Comment by machour** [comment]
@chris-kruining please open a new issue for what you're reporting 🙏🏼

**Comment by mcansh** [comment]
> BTW: I think updating the contributors.yml file should be done automatically after the PR is merged. It's very hard to keep the PR updated as the contributors file is constantly being modified.

we thought about a few different ways to do this instead (form on the website for example), but the problem with doing it after the PR is if you don't end up signing and we merged your work already

**Review by mcansh — APPROVED** [review]
thanks! I started to tinker with this a [bit ago](https://github.com/remix-run/remix/commit/f495544a624608e9a6b6e3efe610e0db38eed8a9), but never got around to opening a PR for it, so thanks again 🙏

can you take a look as well @jacob-ebey

**Comment by connor4312** [comment]
By the way, you can also make breakpoints work by doing something like this in your launch.json:

```
    {
      "type": "node-terminal",
      "request": "launch",
      "name": "Launch",
      "command": "npm run dev:remix",
      "skipFiles": ["<node_internals>/**"],
      "sourceMapPathOverrides": {
        "route:*": "*" // <-- fix up the paths, so route:<path> just becomes <path>
      },
      "outFiles": ["${workspaceFolder}/build/**/*.js"]
    }
```

**Pull request merged**
