### PR TITLE
fix small typo in doc

### PR DESCRIPTION
**Pull request by TheRealAstoo**
Hello 👋

This PR fixes a small typo in the `DEVELOPMENT.md` doc I went by. 😃 

- [x] Docs
- [x] Tests

### CODE REVIEW

**Comment by machour** [comment]
Hey @TheRealAstoo and thank you for taking the time to make this PR.
Would you mind changing its target to `main` instead of `dev` ? Documentation fixes should go directly to `main` 🙏🏼

**Comment by MichaelDeBoey** [comment]
@TheRealAstoo I tried to do it automatically with the GitHub UI, but seems like I did something wrong here 😓

```sh
git reset --hard main
git cherry-pick baa841d
```

**Comment by TheRealAstoo** [comment]
> Hey @TheRealAstoo and thank you for taking the time to make this PR. Would you mind changing its target to `main` instead of `dev` ? Documentation fixes should go directly to `main` 🙏🏼

Sure ! 😃

**Comment by TheRealAstoo** [comment]
> Hey @TheRealAstoo and thank you for taking the time to make this PR. Would you mind changing its target to `main` instead of `dev` ? Documentation fixes should go directly to `main` 🙏🏼

I did it in #2436

**Comment by MichaelDeBoey** [comment]
Closing in favor of #2436

**Pull request closed without merging**
