### PR TITLE
chore(remix-dev): replace `xdm` with `@mdx-js/mdx` v2

### PR DESCRIPTION
**Pull request by jacobwgillespie**
This PR addresses issue #1802 - `xdm` is now deprecated, and all functionality [has been ported to `@mdx-js/mdx`](https://github.com/wooorm/xdm).

Closes: #1802

- [x] ~~Docs~~
- [x] ~~Tests~~

**Testing Strategy:**

All existing tests pass with `yarn test`. Additionally, I created a playground and verified locally that mdx files still build as expected.

### CODE REVIEW

**Comment by belgattitude** [comment]
Thanks,  deasync is very problematic on my side and even more with vercel and node 18. 

Would be very nice to include in the next release 🙏

**Comment by machour** [comment]
@jacobwgillespie could you please rebase this on latest `dev` and fix conflicts? I'll try to get eyes on this PR.

**Comment by jacobwgillespie** [comment]
@machour yep, rebased, thank you!

**Comment by MichaelDeBoey** [comment]
@jacobwgillespie I didn't look into it, but there's also `@mdx-js/esbuild`
https://mdxjs.com/packages/esbuild

Could this replace our own `esbuild` plugin or do we need to keep this custom one?

**Comment by jacobwgillespie** [comment]
Perhaps! I'm not super familiar with Remix's use of MDX internally, mostly just that `xdm` is deprecated and directly replaceable with `@mdx-js/mdx`.

**Comment by MichaelDeBoey** [comment]
Hi @jacobwgillespie!

Are you still interested in getting this one merged?

If so, please rebase onto latest `dev` & resolve conflicts

**Comment by jacobwgillespie** [comment]
@MichaelDeBoey Thanks for the ping, I have rebased onto the latest `dev` 👍

**Review by MichaelDeBoey — APPROVED** [review]

**Comment by jacobwgillespie** [comment]
I'm not sure why the tests are failing, it's upset about `packages/remix-dev/modules.ts` which I don't think is affected by this PR.

**Comment by jacobwgillespie** [comment]
Oh I see it, it's the new `*.mdx` types, let me take a look

**Review by brophdawg11 — APPROVED** [review]

**Pull request merged**
