### PR TITLE
chore(docs): fix typo

### PR DESCRIPTION
**Pull request by stardustrain**
Fix typo in API -> convention documetation.

### CODE REVIEW

**Comment by kentcdodds** [comment]
@stardustrain this PR has an additional commit in it that I don't think you intended to include. Do you want to fix that/make a new one?

**Comment by stardustrain** [comment]
> @stardustrain this PR has an additional commit in it that I don't think you intended to include. Do you want to fix that/make a new one?

@kentcdodds Yes you are right. I will be fix this PR soon.

**Comment by stardustrain** [comment]
@kentcdodds fix at 0d87b45

**Review by kentcdodds — COMMENTED** [review]
Ah! Thanks for fixing it. Now that I see what change you made, in afraid to tell you I already merged another PR that fixed this. Thanks anyway.

**Pull request closed without merging**
