### PR TITLE
fix: fix incorrect loader error message

### LINKED ISSUE #1525: [Bug]: When loader doesn't return a value, the error message mentions `action` instead of `loader`.
### Which Remix packages are impacted?

- [X] `remix` (Remix core)
- [ ] `create-remix`
- [ ] `@remix-run/architect`
- [ ] `@remix-run/cloudflare-workers`
- [ ] `@remix-run/dev`
- [ ] `@remix-run/express`
- [ ] `@remix-run/netlify`
- [ ] `@remix-run/node`
- [ ] `@remix-run/react`
- [ ] `@remix-run/serve`
- [ ] `@remix-run/server-runtime`
- [ ] `@remix-run/vercel`

### What version of Remix are you using?

1.1.1

### What version of Node are you using? Minimum supported version is 14.

14.16.1

### Steps to Reproduce

Create a route with a `loader` that doesn't return a value.

### Expected Behavior

To get the following error:
```
You defined a loader for route "routes/index" but didn't return anything from your `loader` function. Please return a value or `null`.
```

### Actual Behavior

Screenshot 2022-01-17 at 10 41 29

### PR DESCRIPTION
**Pull request by Ehesp**
Fixes #1525

### CODE REVIEW

**Review by jacob-ebey — APPROVED** [review]

**Review by jacob-ebey — CHANGES_REQUESTED** [review]
Please re-target your PR against the "dev" branch and I'll get it merged.

**Comment by silvenon** [comment]
Just FYI, there's a newer PR that does this, but also includes tests. #1530

**Comment by jacob-ebey** [comment]
> Just FYI, there's a newer PR that does this, but also includes tests. #1530

I'm going to go ahead and close this one then. Thank you for the contribution :)

**Comment by Ehesp** [comment]
Closing in favour of https://github.com/remix-run/remix/pull/1530

**Comment by Ehesp** [comment]
Lol beat me too it, no worries.

**Pull request closed without merging**
