### PR TITLE
Use seconds in KV session storage expiration

### LINKED ISSUE #414: Cloudflare KV namespaces expiration seems wrong
Actually, if we set a maxAge to our cloudflare session's cookie, it makes the KV namespace entry being valid for less than a second and that throws an error.

I think there's an issue here:
https://github.com/remix-run/remix/blob/a69a631cb5add72d5fb24211ab2a0be367b6f2fd/packages/remix-cloudflare-workers/sessions/cloudflareKVSessionStorage.ts#L49

Indeed, `.getUTCMilliseconds()` returns milliseconds portion of the time object's value (between 0 and 999) whereas Cloudflare expects a time since UNIX epoch in seconds.

So I think the right code would be something like `.getTime() / 1000`.

### PR DESCRIPTION
**Pull request by GregBrimble**
Fixes #414 and #839.

Description of fix here: https://github.com/remix-run/remix/issues/839#issuecomment-986295640.

### CODE REVIEW

**Comment by GregBrimble** [comment]
I've got other PRs open which add me as a contributor, so I won't add that here to avoid conflicts.

**Review by kentcdodds — APPROVED** [review]
LGTM. @jacob-ebey?

**Review by mcansh — APPROVED** [review]

**Comment by kentcdodds** [comment]
I think we can get this one merged. Would you mind adding yourself as a contributor on this PR? We'll handle merge conflicts on the other PRs.

**Comment by GregBrimble** [comment]
Duck landing

**Comment by kentcdodds** [comment]
@chaance I mistakenly marked this one as a `feat`. Should be a `fix`.

**Comment by kentcdodds** [comment]
Thank you @GregBrimble! We're looking at your other PRs as well 👍

**Pull request merged**
