### PR TITLE
docs(guides/styling): fix Tailwind CSS installation instructions

### PR DESCRIPTION
**Pull request by adamwathan**
Doing this from my phone while getting my kid ready for school forgive me for not being able to fill in the template 😅

### CODE REVIEW

**Review by MichaelDeBoey — APPROVED** [review]

**Comment by MichaelDeBoey** [comment]
@adamwathan We can only merge this PR if you sign the CLA.

Since you're at you're phone, I'm happy to add your name to the `contributors.yml` file if you want.

**Review by MichaelDeBoey — APPROVED** [review]

**Review by machour — APPROVED** [review]
Thank you @adamwathan 🙏🏼

**Comment by machour** [comment]
oh, we just need you to sign the CLA by adding your username to `contributors.md`, and target the `main` branch instead of `dev`

**Comment by adamwathan** [comment]
> oh, we just need you to sign the CLA by adding your username to `contributors.md`, and target the `main` branch instead of `dev`

Hey! The `main` branch doesn't have the mistake, it's only present in the `dev` branch and was just introduced in this PR:

https://github.com/remix-run/remix/pull/5229

**Pull request merged**
