### PR TITLE
feat(codemod): replace-remix-imports

### PR DESCRIPTION
**Pull request by pcattori**
Throw an error if Remix is a:
- Side-effect import: `import 'remix'` (TODO)
- Default import: `import Remix from 'remix'`
- Namespace import: `import * as Remix from 'remix'`
The error should direct users to replace these^ imports with named imports.

Example input:

```tsx
import { isCookie, createCookie, RemixServer, Meta } from 'remix'
import { ScrollRestoration, createCookie as blah, yo, Link } from 'remix'
import type { ActionFunction } from 'remix'
import type { LoaderFunction as LF, FormProps as FP  } from 'remix'
import React, * as blah2 from 'react'

import { hook } from './lib'

const a = 1
console.log('blah')
```

- [ ] Docs
- [ ] Tests

### CODE REVIEW

**Comment by pcattori** [comment]
Added a commit applying the codemod to `examples/`

**Comment by mjackson** [comment]
Can we have the codemod also remove the `remix` entry in package.json? /cc @MichaelDeBoey

**Comment by pcattori** [comment]
> Can we have the codemod also remove the `remix` entry in package.json? /cc @MichaelDeBoey

The transform itself is for modifying javascript packages, but the `codemod` command that calls the transform can certainly do that

**Comment by MichaelDeBoey** [comment]
> the `codemod` command that calls the transform can certainly do that.

That's indeed what I was thinking too

**Comment by MichaelDeBoey** [comment]
@pcattori Since #2430 is merged & we have #2575 & #2585 run with latest version of the codemod, I think we can close this one?

**Pull request closed without merging**
