### PR TITLE
bug: <Form> submit changes url immediately upon submission

### PR DESCRIPTION
**Pull request by smerchek**
Submitting a normal `<form>` does not have this behavior. I'd expect the url to be unchanged until the action responds with a redirect or other response.

- [ ] Docs
- [X] Tests

### CODE REVIEW

**Comment by zipme** [comment]
Any updates? Using `useFetch` doesn't have this problem though.

**Comment by machour** [comment]
@mcansh will this be fixed by the change in 6.4 described by Ryan here? https://github.com/remix-run/remix/pull/2110#issuecomment-1180806310 🤔

**Comment by kiliman** [comment]
@zipme Unlike forms, fetchers are **not** navigations, so they will never change the URL.

**Comment by chaance** [comment]
If this is still an issue it should be fixed and tested in React Router. Mind checking that out and opening a new issue there if needed?

**Pull request closed without merging**
