### PR TITLE
fix: add cache control for vercel static assets

### PR DESCRIPTION
**Pull request by jacob-ebey**

### CODE REVIEW

**Comment by mcansh** [comment]
these are handled automatically by vercel :) https://github.com/vercel/vercel/blob/main/packages/frameworks/src/frameworks.ts#L257

**Comment by jacob-ebey** [comment]
> these are handled automatically by vercel :) https://github.com/vercel/vercel/blob/main/packages/frameworks/src/frameworks.ts#L257

I'll double check but it seemed like they were not there in my deployment.

**Comment by mcansh** [comment]
mine appear to have proper cache control image

**Comment by jacob-ebey** [comment]
@mcansh here is a barebones deployment done through the Vercel UX: https://github.com/jacob-ebey/dynamic-css-with-remix-resource-routes https://dynamic-css-with-remix-resource-routes.vercel.app/demos/theme

There is a `cache-control: public, max-age=0, must-revalidate` on all the static assets.

**Comment by leo** [comment]
Thank you for this PR!

I suggest closing it, though, as we're working on a fix in https://github.com/vercel/vercel/pull/7064.

**Pull request closed without merging**
