### PR TITLE
Remove unneeded while loop

### PR DESCRIPTION
**Pull request by gavriguy**
Removing  unneeded while loop in the Upstash example.

Thanks @donavon for letting me know.

### CODE REVIEW

**Comment by donavon** [comment]
Thank YOU for this very useful example.

**Review by LANCENET — APPROVED** [review]

**Comment by ryanflorence** [comment]
why was that there in the first place? wouldn't this just totally crash a server?

**Comment by donavon** [comment]
@ryanflorence no b'cuz is returning inside of the loop. It's just unnecessary and confusing.

**Comment by kentcdodds** [comment]
I have no idea how I missed this 😅 thanks for cleaning this up

**Comment by donavon** [comment]
Not a problem. I saw it and went whoa!

**Pull request merged**
