### PR TITLE
fix(remix-deno): add messages to catch not found error

### PR DESCRIPTION
**Pull request by sstiglitz**
Closes: #5625

- [ ] Docs
- [ ] Tests

Testing Strategy:

Installed patched version of `@remix-run/deno` in my project, started server. Was able to navigate to root route successfully.

### CODE REVIEW

**Review by MichaelDeBoey — APPROVED** [review]

**Comment by schoening** [comment]
I would really like to use Remix + Deno Deploy.

Could someone please merge in this approved PR?
Pretty please with sugar on top 🍰

**Comment by machour** [comment]
@schoening might already have been fixed in https://github.com/denoland/deno/pull/17958
Could you give deno 1.32.X a try and report if you still see the problem?

**Comment by machour** [comment]
Confirmed that the issue have been fixed in deno

**Comment by schoening** [comment]
@machour I have tested it now and indeed everything is working now :blush:

**Pull request closed without merging**
