### PR TITLE
feat(remix-dev): use external Vercel template

### PR DESCRIPTION
**Pull request by Ethan-Arrowood**
This PR updates the template that remix uses when you call the create command. Wanted to propose this new solution where it will download the template we maintain. If y'all would like to still own the template I'd be happy to scrap these changes and just send a PR that copy-paste from our template. 

Testing Strategy:

Template is tested in Vercel's repo's integration tests.

### CODE REVIEW

**Comment by Ethan-Arrowood** [comment]
Had to remove self temporarily from CLA. Don't expect it to be an issue but need to get explicit internal approval before I "sign" it. Whoops!

**Comment by MichaelDeBoey** [comment]
Hi @Ethan-Arrowood!

Are you still interested in getting this one merged?

If so, please rebase onto latest `dev` & resolve conflicts

**Review by MichaelDeBoey — CHANGES_REQUESTED** [review]
@Ethan-Arrowood Since this is also a code change, could you please rebase onto latest `dev` & set base branch to `dev` as well?

**Comment by Ethan-Arrowood** [comment]
Fixed up 👍

**Review by sergiodxa — APPROVED** [review]
The template being owned by Vercel the same way you own the adapter makes lots of sense 👍

**Comment by Ethan-Arrowood** [comment]
Hi folks, whats the status on this? I fixed it up previously and it never merged. Now its conflicting again. If I fix the merge conflicts can we land this?

**Comment by Ethan-Arrowood** [comment]
Fixed merge conflicts 👍 Lets get this merged 🚢

**Comment by MichaelDeBoey** [comment]
Superseded by #6784

**Pull request closed without merging**
