### PR TITLE
chore: dedupe `yarn.lock`

### PR DESCRIPTION
**Pull request by MichaelDeBoey**
This will make PRs like https://github.com/remix-run/remix/pull/6038 or https://github.com/remix-run/remix/pull/6044 less necessary

Did this by running `npx yarn-deduplicate && rm -rf ./node_modules && yarn`

- https://github.com/scinos/yarn-deduplicate
- https://npm.im/yarn-deduplicate

### CODE REVIEW

**Comment by mcansh** [comment]
sweet!

**Comment by mcansh** [comment]
might he nice to have this run on push with changes to ./packages/*/package.json and commit if there's a diff

**Comment by MichaelDeBoey** [comment]
> might he nice to have this run on push with changes to ./packages/*/package.json and commit if there's a diff

I think we just need to check against changes in `yarn.lock` tbh 🤔

We could do that in a follow-up PR I think?

**Review by mcansh — APPROVED** [review]

**Comment by MichaelDeBoey** [comment]
@mcansh They seem to be gone if we keep `@types/node@*` at v16 🤔

Should we fix the code or keep it at v16 (for now) until we are fully transitioned to v18 in @jacob-ebey's #5868?

**Comment by MichaelDeBoey** [comment]
@mcansh The problem seemed to be that `NodeOnDiskFile` doesn't have a `prototype` property, but after implementing it, we still get
> Type 'NodeOnDiskFile' provides no match for the signature 'new (blobParts?: BlobPart[] | undefined, options?: BlobPropertyBag | undefined): Blob'.

Since @jacob-ebey is the creator of the class, maybe he can point me/us into the right direction here
I tried a lot, but can't seem to find a solution to make this work tbh 🤔

**Comment by MichaelDeBoey** [comment]
@mcansh It appears @dpobel already has the TS error about the `prototype` property on a fresh install (see https://github.com/remix-run/remix/issues/6119#issuecomment-1521288835), so we should definitely find a solution here 👀

**Comment by MichaelDeBoey** [comment]
@brophdawg11 I managed to (temporarily) "fix" the type errors with `NodeOnDiskFile` that were caused due to the TS regression with `File` class (see https://github.com/microsoft/TypeScript/issues/52166)

These changes are only here to make TS happy again and have no impact on the actual code itself

**Comment by MichaelDeBoey** [comment]
Merging this one because @jacob-ebey approved #7044

**Pull request merged**
