### PR TITLE
chore: Minor rephrasing in the MDX guide

### PR DESCRIPTION
**Pull request by silvenon**
Telling people that they won't ever reach 10 posts might come across as a little discouraging. My blog currently has 22 posts, and I still have a lot more to say. 😊 But I totally get the point that having 10-20 import statements should be totally fine and people shouldn't immediately start freaking out about scalability as if they're building a blogging platform. 😄

### CODE REVIEW

**Comment by tomByrer** [comment]
Also weird to say:

> you don't have to rebuild and redeploy your blog every time you fix a typo

That IMHO is an issue for Remix to solve without the site manager needing to solve it.

**Comment by silvenon** [comment]
I'm not sure I understand, could you elaborate?

**Review by MichaelDeBoey — APPROVED** [review]

**Comment by Dandan821** [comment]
https://vuuzletvph.com/heads-up-vuco-bounty-programs-are-coming-your-way/

**Comment by Dandan821** [comment]
https://vuuzletvph.com/heads-up-vuco-bounty-programs-are-coming-your-way/

**Comment by Dandan821** [comment]
https://vuuzletvph.com/heads-up-vuco-bounty-programs-are-coming-your-way/

**Comment by Dandan821** [comment]
https://vuuzletvph.com/heads-up-vuco-bounty-programs-are-coming-your-way/

**Pull request merged**
