### PR TITLE
docs(api/remix): fix link to `PrefetchPageLinks` page

### PR DESCRIPTION
**Pull request by MichaelDeBoey**

### CODE REVIEW

**Review by machour — COMMENTED** [review]
How about moved-68 instead like the rest of the document for consistency?

**Comment by MichaelDeBoey** [comment]
@machour This will be auto-fixed by the format workflow

Don't know if it will shift all links or not, that's why I kept it as a normal link

**Review by machour — APPROVED** [review]
Let's give it a try 👀

**Comment by MichaelDeBoey** [comment]
@machour As expected: https://github.com/remix-run/remix/commit/534e1ec071f17654a4db8622e30d6ff70548ce26

**Comment by machour** [comment]
Always learning new things with you 😄

**Pull request merged**
