### PR TITLE
fix: `useLoaderData` in parent route without boundary handlers should return data when child throws an error

### PR DESCRIPTION
**Pull request by andmayorov**
Currently there is a bug which easier to explain by this example:

1. We have 3 nested routes
```ts
let matches = ["root", "/jokes", "/jokes/$jokeId"];
```
2. `root` and `/jokes/$jokeId` modules export `CatchBoundary` function while `/jokes` doesn't
3. Now we throw an error inside action in `/jokes/$jokeId` module and expect  `CatchBoundary` to handle it.
4. But instead we get some different kind of error because `useLoaderData` inside `/jokes` returns `undefined`. And error is handles by `ErrorBoundary` inside `root` module instead.

The reason why it happens is that at the moment we use `getMatchesUpToDeepestBoundary` to filter out `matchesToLoad`. We expect `matchesToLoad` to contain `["root", "/jokes"]` but instead it contains `["root"]`.

Since `/jokes` doesn't have `CatchBoundary` `getMatchesUpToDeepestBoundary` ignores it. Therefore it doesn't initialise `/jokes`'s `loader` even though it didn't throw any errors and Remix still tries to render it.

Related issue: https://github.com/remix-run/remix/issues/599

### CODE REVIEW

**Comment by ryanflorence** [comment]
@andmayorov thanks for your work here! I think we've fixed this though.

@jacob-ebey I think your recent changes fix this?

If not, please re-open, either one of you :)

**Comment by sbking** [comment]
@ryanflorence This is still happening when following the official Jokes tutorial as of today. It happens in the [Expected Errors](https://remix.run/docs/en/v1/tutorials/jokes#expected-errors) section, when you try to delete a joke that you don't own.

**Comment by JudeTejada** [comment]
any updates on this?

**Comment by llwt** [comment]
I just ran into this as well working through the tutorial today.

**Comment by machour** [comment]
Too many things have changed, another PR needs to be produced if the problem persists.
Meanwhile, #599 is still open to track the bug, please comment on the issue instead 🙌🏼

**Comment by nikshirobokov** [comment]
> Problem definitely still exists as of June 2022.

Yep! Confirmed. 
Remix version `1.6.2`

**Comment by machour** [comment]
Please read through https://github.com/remix-run/remix/issues/599 and open a new issue if the problem still exists.
Commenting on a closed PR isn't likely to get you anywhere.

**Pull request closed without merging**
