### PR TITLE
Added engine node version in package.json for cloudflare-pages template

### PR DESCRIPTION
**Pull request by zhe**
"cloudflare-pages" template uses wrangler2 (`beta` at this moment) which requires `node` version at least `16.7.0`, see: https://github.com/cloudflare/wrangler2/pull/271, https://github.com/remix-run/remix/pull/1391 or https://github.com/cloudflare/wrangler2/blob/575962d2f1c59aa07ac7398500e8cc7e0fde9e7f/package.json#L43 

If using node 14, the `dev` script may fail.

Thinking it might be nice to specify node version in the `package.json` `engines` to give users a possible friendly message in the terminal, especially using `yarn` or `pnpm`

```
error remix-app-template@: The engine "node" is incompatible with this module. Expected version ">=16.7.0". Got "14.17.6"
```

```
 WARN  Unsupported engine: wanted: {"node":">=16.7.0"} (current: {"node":"v14.17.6","pnpm":"6.31.0"})
```

### CODE REVIEW

**Comment by MichaelDeBoey** [comment]
@zhe Changes to `templates` should go to `main` branch.

**Comment by zhe** [comment]
@MichaelDeBoey thanks for the comment. The base has been changed to `main` branch.

**Comment by zhe** [comment]
@MichaelDeBoey sorry, this PR looks kinda messy now - many extra commits and files changes, since it started from `dev` branch as source branch, and now it's going to `main`. I'm happy to close this one, or do you have any suggestion? Thanks

**Comment by MichaelDeBoey** [comment]
@zhe I think it would be best to create a new PR (from a separate branch that's branching of off `main`) and cherry-pick 4263a38 in that new branch.

**Comment by zhe** [comment]
@MichaelDeBoey thanks for your suggestion. I've made a new PR here https://github.com/remix-run/remix/pull/2457.

**Pull request closed without merging**
