### PR TITLE
Feature/basename

### PR DESCRIPTION
**Pull request by yracnet**
I have implemented the feature described on the  https://github.com/remix-run/remix/discussions/2891.

This include the serverBasename attribute on remix.config.js for declare a prefix to URL
> serverBasename default value is ""
> fix deploy on path server (basename)
> fix the navegation in client side or server side components

### CODE REVIEW

**Comment by machour** [comment]
Refs #2996

**Comment by gerbyzation** [comment]
This would be a great feature to have in remix. If I can help with making this happen let me know!

**Comment by yracnet** [comment]
Thanks, but I dont know what is the next step.

**Comment by gerbyzation** [comment]
@yracnet As mentioned in this comment I think they are waiting for some unrelated changes that have snuck in to be removed: https://github.com/remix-run/remix/pull/4459#pullrequestreview-1162370075 For example `decisions/0006-linear-workflow.md` is added as part of this PR but doesn't seem related to the scope?

**Comment by hemangsk** [comment]
@yracnet , First of all great job, this is such a useful feature.

Do I have your permission to fork this branch and do the required changes (removing unrelated commits) and make the PR merge ready? We really need this feature and incase you're busy, I'll be more than willing to get things moving here 🙏

**Comment by yracnet** [comment]
Hi @hemangsk thanks, I have merged my branch with the las change from dev, I run the test. I will wait to approval my changes. thanks

**Comment by gerbyzation** [comment]
@yracnet thanks for updating your branch! Unfortunately there are still unrelated changes in the diff. As @hemangsk and I have offered we're happy to port your work to a clean branch to get this shipped if you don't mind

**Comment by yracnet** [comment]
Thanks, I will send a new pr with the clean branch from dev.

**Comment by asevenm** [comment]
v1.18.0 not include this feature ?

**Pull request closed without merging**
