### PR TITLE
ci: update deployment testing infra

### PR DESCRIPTION
**Pull request by mcansh**
let's clean up after ourselves, some providers limit how many resources you can have,
AWS has a 100 S3 Bucket limit and CF Pages limits you to 100 pages projects – others may have limits as well, so lets just remove the app when we're done

Signed-off-by: Logan McAnsh <logan@mcan.sh>

Closes: #

- [ ] Docs
- [ ] Tests

Testing Strategy:

### CODE REVIEW

**Review by MichaelDeBoey — APPROVED** [review]

**Comment by kentcdodds** [comment]
Does the client need to be reused? Maybe we can break things out into other files if necessary?

**Comment by mcansh** [comment]
> 

it was just a one time thing to clear out older deployments, we have about 6 days worth since i opened and ran the deletion script (that I've since removed 😅), but i can manually remove those

**Comment by kentcdodds** [comment]
Got it 👍 Sounds good then. I think we can merge this. Thanks!

**Review by kentcdodds — APPROVED** [review]
Solid 👍 Thank you!

**Pull request merged**
