### PR TITLE
fix(remix-dev): dont use nullish coalescing in cli to support node 12

### PR DESCRIPTION
**Pull request by mcansh**
Signed-off-by: Logan McAnsh <logan@mcan.sh>

Closes: #

- [ ] Docs
- [ ] Tests

Testing Strategy:

### CODE REVIEW

**Comment by MichaelDeBoey** [comment]
I don't think this is necessary, as the very first thing the CLI is checking is if the user is using Node v14 or higher 🤔

https://github.com/remix-run/remix/blob/eb4e899b1129fd96eba744c2342dbe61669227d8/packages/remix-dev/cli/run.ts#L145-L152

**Review by MichaelDeBoey — COMMENTED** [review]
I don't think this is necessary, as the very first thing the CLI is checking is if the user is using Node v14 or higher 🤔

https://github.com/remix-run/remix/blob/eb4e899b1129fd96eba744c2342dbe61669227d8/packages/remix-dev/cli/run.ts#L145-L152

**Comment by mcansh** [comment]
it is indeed needed image

**Comment by MichaelDeBoey** [comment]
Hmmm that's weird, it should already stop at the thrown error, no?
The `getPreferredPackageManager` function isn't called yet there 🤔

**Comment by mcansh** [comment]
> The `getPreferredPackageManager` function isn't called yet there 🤔

i don't think it matters if or when it's called, but when it's parsed it errors out

**Comment by MichaelDeBoey** [comment]
> but when it's parsed it errors out

Does that mean we can _never_ have v14 syntax?
Or is that only in the `packages/remix-dev/cli/run.ts` file?

**Comment by sergiodxa** [comment]
Node v12 LTS maintenance life ended last month, I don’t think Remix should support it, even if it fails without showing an specific error

**Comment by mcansh** [comment]
> Node v12 LTS maintenance life ended last month, I don’t think Remix should support it, even if it fails without showing an specific error

we only support it enough to say we don't support it 😅

**Comment by MichaelDeBoey** [comment]
Questions remains: what about earlier versions?

**Comment by MichaelDeBoey** [comment]
@mcansh This function has been extracted into a separate file in #2864, so I think this isn't necessary anymore? 🤔

**Comment by mcansh** [comment]
yup looks good now :) image

**Pull request closed without merging**
