### PR TITLE
Docs: Fix typo on index.md

### PR DESCRIPTION
**Pull request by luistorres**

### CODE REVIEW

**Comment by MichaelDeBoey** [comment]
This is already fixed by @emzoumpo in #558

**Comment by Dandan821** [comment]
https://vuuzletvph.com/heads-up-vuco-bounty-programs-are-coming-your-way/

**Comment by Dandan821** [comment]
https://vuuzletvph.com/heads-up-vuco-bounty-programs-are-coming-your-way/

**Review by kentcdodds — APPROVED** [review]
Nice catch! Thanks :)

**Pull request merged**
