### PR TITLE
feat: empty-outdir-before-build-or-rebuild

### PR DESCRIPTION
**Pull request by chenc041**
in dev mode, change file will generate repeat file and that files is useless, so i hope before build or rebuilding cleanup the outdir, so i make this PR

### Change Remix packages
- [x] @remix-run/dev

### Expected Behavior
before build or rebuilding cleanup the outdir

### Actual Behavior
change file will generate repeat file with different hash

### CODE REVIEW

**Comment by hanayashiki** [comment]
I hope this commit can be merged soon!

**Comment by chenc041** [comment]
> I hope this commit can be merged soon!

Has passed a long time 😂

**Comment by chenc041** [comment]
@mjackson hi jackson, If there is no problem, can you merge this PR as soon as possible?

**Comment by chaance** [comment]
Hello! Very sorry we didn't get to review this in a timely fashioned. I'm not sure we want to clean out the directories between each rebuild in dev mode as that would incur some performance cost as projects grow. Closing for now since it's not actionable, but if there's anything we could do to improve the dev experience feel free to open a discussion for a proposal.

**Comment by kiliman** [comment]
I agree. I simply run `clean` when I run `dev`. So it cleans before each new dev *session*, but doesn't clean on each rebuild since that wouldn't efficiently reuse the build cache.
```json
"scripts": {
  "clean": "rimraf build public/build",
  "dev": "npm run clean && run-p dev:*",
  "dev:css": "...",
  "dev:remix": "...",
}
```

**Pull request closed without merging**
