### PR TITLE
fix(remix-dev): Update create-remix to use the new examples repository

### PR DESCRIPTION
**Pull request by machour**
Also removed some now obsolete eslint rules

### CODE REVIEW

**Comment by machour** [comment]
I'm hitting a snag here: My changes to `create-remix` works in reality, but as far as I understand the testing process, the mock is trying to read from the removed folder.

Any guidance would be appreciated :)

**Comment by chaance** [comment]
Thanks @machour, I'll take a look at this tomorrow and see if I can help with the tests.

**Review by chaance — CHANGES_REQUESTED** [review]
Pressed approve too early—looks like we've got some failing test cases here. Let's get those patched up and I'll merge this for the next release.

Also: could we add a changeset noting the bug fix since this is broken at the moment?

**Comment by machour** [comment]
@chaance You were supposed to help for the tests 😅 (see your previous reply)

As commented, the problem is that tests were mocking the request to `https://github.com/remix-run/remix/tree/main/examples` by using the `examples` folder from the currently checked out repo in the workflow.

Now that we moved examples to their own repository, this mock isn't usable anymore.

I suppose I'll have to create a `basic-example.tar.gz` fixture and configure msw to correctly respond with that mock, but I've been trying and failing to make things work.

Can someone guide me, or take over this last step from me? (I'll understand what I was missing from the diff)

**Comment by chaance** [comment]
@machour looking at it this morning!

**Comment by mcansh** [comment]
taking a look into this now :)

**Review by mcansh — APPROVED** [review]

**Comment by machour** [comment]
Thank you @mcansh !

**Comment by chaance** [comment]
LGTM! @machour can we get conflicts resolved so I can merge this week?

**Review by chaance — APPROVED** [review]

**Pull request merged**
