### PR TITLE
chore(tutorials/jokes): prefetch `new` page

### PR DESCRIPTION
**Pull request by MichaelDeBoey**
Fixes https://github.com/remix-run/remix/discussions/961

### CODE REVIEW

**Comment by ryanflorence** [comment]
@kentcdodds you want this in the tutorial? If so go ahead and merge :)

**Review by kentcdodds — APPROVED** [review]
Yeah, this is probably a good idea 👍

**Comment by kentcdodds** [comment]
Actually, in all cases, these code blocks come before we add JS to the page so it won't do anything. There's a section in the tutorial where I describe prefetching and I suppose we could mention you could add it to the `new` link and even add a code block there if you'd like: https://remix.run/docs/en/v1/tutorials/jokes#prefetching

**Comment by ryanflorence** [comment]
Ah yeah, it introduces the concept already, so I think we're good.

**Pull request closed without merging**
