### PR TITLE
fix(remix-node): stop `maxFileSize` being exceeded causing the server to exit

### LINKED ISSUE #2230: Server exits when `maxFileSize` is exceeded when using `unstable_createFileUploadHandler()`
### What version of Remix are you using?

1.2.3

### Steps to Reproduce

1. Do a standard install with default options by running `npx create-remix@latest`.
2. Start the server with `yarn dev`.
3. Replace `index.tsx` with the following code.

<details>
<summary>Click to show</summary>

```ts
import {
  ActionFunction,
  Form,
  unstable_createFileUploadHandler,
  unstable_parseMultipartFormData,
} from "remix";

const uploadHandler = unstable_createFileUploadHandler({
  directory: "public/uploads",
  file: ({ filename }) => filename,
  maxFileSize: 1_000_000,
});

export const action: ActionFunction = async ({ request }) => {
  const formData = await unstable_parseMultipartFormData(
    request,
    uploadHandler
  );

  const file = formData.get("selected-file");

  return { file };
};

export default function Index() {
  return (
    <div style={{ fontFamily: "system-ui, sans-serif", lineHeight: "1.4" }}>
      <h1>Upload limit demo</h1>
      <Form method="post" encType="multipart/form-data">
        <input type="file" id="selected-file" name="selected-file" />
        <button>Upload</button>
      </Form>
    </div>
  );
}
```
</details>

4. Upload a file that is larger than 1MB.

### Expected Behavior

The server to continue running. It should not exit as it does currently. Results in `ERR_CONNECTION_REFUSED` in browser.

### Actual Behavior

The server will exit. Console output:

```
There was an error running the action for route routes/index
Error: Field "selected-file" exceeded upload size of 1000000 bytes.
    at Meter._transform (/path/to/app/node_modules/@remix-run/node/upload/meter.js:30:23)
    at Meter.Transform._read (internal/streams/transform.js:205:10)
    at Meter.Readable.read (internal/streams/readable.js:462:10)
    at flow (internal/streams/readable.js:982:34)
    at WriteStream.pipeOnDrainFunctionResult (internal/streams/readable.js:806:7)
    at WriteStream.emit (events.js:400:28)
    at afterWrite (internal/streams/writable.js:461:12)
    at onwrite (internal/streams/writable.js:446:7)
    at internal/fs/streams.js:368:5
    at FSReqCallback.wrapper [as oncomplete] (fs.js:660:5)
Error: Field "selected-file" exceeded upload size of 1000000 bytes.
    at Meter._transform (/path/to/app/node_modules/@remix-run/node/upload/meter.js:30:23)
    at Meter.Transform._read (internal/streams/transform.js:205:10)
    at Meter.Readable.read (internal/streams/readable.js:462:10)
    at flow (internal/streams/readable.js:982:34)
    at WriteStream.pipeOnDrainFunctionResult (internal/streams/readable.js:806:7)
    at WriteStream.emit (events.js:400:28)
    at afterWrite (internal/streams/writable.js:461:12)
    at onwrite (internal/streams/writable.js:446:7)
    at internal/fs/streams.js:368:5
    at FSReqCallback.wrapper [as oncomplete] (fs.js:660:5)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

I have found if I comment out this then it does not happen and remains running as expected:
https://github.com/remix-run/remix/blob/8a056ee4d17a1c4ecd2831196283a5cade1852c4/packages/remix-node/parseMultipartFormData.ts#L80-L83

Also, I have shared this on Discord #help where 1 person came forward as they had the same issue and was wondering if I had managed to resolve it. Someone else also replicated the issue successfully.

### PR DESCRIPTION
**Pull request by uwuru**
I am not sure if this is all that is needed (as we're using `await` to call `uploadHandler()` so do we not need to do this?) or if I'm missing something and we should be doing more checks or something and still throwing. Would like to kick off fixing it though.

- [x] Docs - N/A
- [ ] Tests - Happy to look into how to approach this if needed and PR progresses

Fixes #2230

### CODE REVIEW

**Comment by swwind** [comment]
Surely, error was already thrown into `busboy.emit("error", error)` and there is no need to throw it again.

badly need this to be fixed

**Comment by mjackson** [comment]
Can you please include a test here? It would be nice to test what actually happens when a file upload is too large.

**Comment by uwuru** [comment]
@mjackson Done, though this still passes even when you revert the fix of removing `throw error` because it depends how the parent process handles the uncaught error.

Jest behaves as follows with the removed `throw error` put back, and carries on testing. In comparison to the dev server (in the case of this issue/PR, not tried it with others), whose process exits:

```bash
...
 PASS   node  packages/remix-node/__tests__/parseMultipartFormData-test.ts
(node:51136) UnhandledPromiseRejectionWarning: Error: Field "file" exceeded upload size of 1 bytes.
(Use `node --trace-warnings ...` to show where the warning was created)
(node:51136) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:51136) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
 PASS   node  packages/remix-node/__tests__/sessions-test.ts
...
```

**Comment by uwuru** [comment]
I have noticed the integration tests are now failing and there was in fact already a test there for this (with out javascript - and another one with javascript but that's being skipped as it isn't working as expected). Which was passing and is now failing 🤔 I will try and look over the weekend. Interested to hear if any one has any thoughts though.

**Comment by a3diti** [comment]
Already fixed it with this patch https://github.com/remix-run/remix/issues/2230#issuecomment-1100039432

**Comment by mikkpokk** [comment]
@uwuru File `/integration/action-test.ts` on line 73 you should modify action behaviour to response with status code 500. Removing `throw error;` from the file `parseMultipartFormData.ts` also passes the request with status code 200 without self-handling the error :)

That is the reason the test fails. It expects 500 but gets 200.

**Comment by vedantroy** [comment]
While this PR is getting merged -- will my production server be affected?

**Comment by machour** [comment]
@uwuru can you please update your PR according to @mikkpokk feedback? A `422 - Unprocessable Entity` error seems like the way to go

**Comment by MichaelDeBoey** [comment]
@uwuru Could you please rebase your branch onto latest `dev` & resolve conflicts?

**Comment by MichaelDeBoey** [comment]
@uwuru Could you please rebase your branch onto latest `dev` & resolve conflicts?

**Comment by chaance** [comment]
Looks like this has diverged a good deal since our current implementation of `unstable_parseMultipartFormData` moved to `@remix-run/server-runtime`. Closing for now, but feel free to open a new PR if the issue persists.

**Pull request closed without merging**
