### PR TITLE
Update single fetch deprecation notice to also include info about null

### PR DESCRIPTION
**Pull request by JakeGinnivan**
Resource routes can no longer just return null, call this out in the deprecation notice.

It just took me a minute to realise it was the null which was triggering the message.

### CODE REVIEW

**Comment by JakeGinnivan** [comment]
I'll update the tests if this is actually correct. Let me know.

**Comment by JakeGinnivan** [comment]
Done @brophdawg11. Thanks

Let me know if I need to squash/apply conventional commits. This started as a bit of a drive by, haha

**Comment by brophdawg11** [comment]
Looks good!  No need to change any commits - I'll squash-merge the PR.

Would you mind adding a [changeset](https://github.com/remix-run/remix/pull/10145#issuecomment-2425682413) as well?  Should be able to just type `pnpm changeset` and follow the prompts for a patch change for the server-runtime package

**Comment by JakeGinnivan** [comment]
Done @brophdawg11. Thanks for your help

**Review by brophdawg11 — APPROVED** [review]

**Pull request merged**
