### PR TITLE
feat: add flat routes convention

### PR DESCRIPTION
**Pull request by kiliman**
Closes: #4483

- [ ] Docs
- [ ] Tests

This is the initial PR to add flat routes convention

Testing Strategy:

### CODE REVIEW

**Comment by kiliman** [comment]
Ok, here's my initial PR. I simply copied over my flatRoutes function. I will work on integrating with existing config and updating the tests.

**Comment by ryanflorence** [comment]
We'll want it behind a future flag, too. Let's go with:

```js
// remix.config.js
{
  future: {
    v2_routeConvention: true
  }
}
```

Future flags were merged here: https://github.com/remix-run/remix/pull/4566

If you run into questions about future flags, reach out to @chaance :)

**Comment by machour** [comment]
@ryanflorence regarding the flag name, have you reached a conclusion regarding keeping or removing the current convention in V2? (Question raised in the RFC)

We may want to change the flag name to `v2_flatRoutesConvention` if we keep both.

**Comment by kiliman** [comment]
@ryanflorence ok so the plan is if the feature flag is true for flat routes, then this will automatically use the flat routes convention instead of the default (i.e., no need to specify the `routes` config option). Correct?

**Comment by ryanflorence** [comment]
Let's move forward as if this is the only built-in convention for v2, so let's use `v2_routeConvention`.

As folks start updating we can revisit if it maybe shouldn't be the only convention, or even the default. I suspect people will prefer it, though.

**Comment by kiliman** [comment]
Ok, I've pushed the latest version. This also includes the *hybrid* routes.

I think this gives you the best of both worlds. You can still organize with nested folders, but you also get colocation.

**Comment by machour** [comment]
@kiliman Tested hybrid routes on 0.5.0, works like a charm 👌🏼 Thank you so much for this.

**Comment by mcansh** [comment]
closed in favor of #4880 (which includes these commits)

**Pull request closed without merging**
