### PR TITLE
fix(remix-dev): Use normalized file path when analyzing flat routes

### LINKED ISSUE #5672: Remix 1.14.0 flat route folders with _index include everything inside as child routes
### What version of Remix are you using?

1.14.0

### Are all your remix dependencies & dev-dependencies using the same version?

- [X] Yes

### Steps to Reproduce

Create a fresh remix site via `npx create-remix@latest` using all defaults.
Enable flat routes in `remix.config.js`

Rename `index.tsx` to `_index.tsx` to use conventions for flat routes.

Add a folder flat route `some-folder._index/route.tsx`
Add a basic file in your `some-folder._index` like `utils.ts` with any exports

`npm run dev` or even `npx remix routes` and you'll get an error:
```
Error: Child routes are not allowed in index routes. Please remove child routes of some-folder._index
```

### Expected Behavior

I can have a flat route folder ending in `_index` that allows me to co-locate files within it and doesn't count those as child routes.

### Actual Behavior

```
Error: Child routes are not allowed in index routes. Please remove child routes of some-folder._index
```

### PR DESCRIPTION
**Pull request by michaelgmcd**
Fixes #5672.

I've added a test in remix-dev for the functionality as well. Before this change, this test failed on Windows and passed on MacOS.

### CODE REVIEW

**Comment by michaelgmcd** [comment]
The test failures don't seem related. Can someone with some more context take a look?

**Comment by kevinbailey25** [comment]
Any update on this fix anyone? This is preventing me from being on the latest update of remix. Stuck on v1.11 currently.

**Comment by michaelgmcd** [comment]
> @michaelgmcd, can you make these changes against the `dev` branch instead?

Changed the branch and rebased.

**Comment by mcansh** [comment]
> > @michaelgmcd, can you make these changes against the `dev` branch instead?
> 
> Changed the branch and rebased.

perfect, thank you! we're doing some performance auditing for various parts of the cli, flat routes being one of them so i'll make sure we got this over there as well

**Comment by ronnylt** [comment]
Not sure if https://github.com/remix-run/remix/issues/5779 is also related to this.

**Comment by michaelgmcd** [comment]
Seems like it

**Pull request merged**
