### PR TITLE
Fix: break switch cases to show intended message

### PR DESCRIPTION
**Pull request by thomasmarr**

### CODE REVIEW

**Comment by thomasmarr** [comment]
I'm sure I will not mind signing the CLA, but the link to it is giving me a 404 (same for the contributing guide).

**Comment by mcansh** [comment]
sorry @thomasmarr I'll look into the 404 issue, here's the [contributing guide](https://github.com/thomasmarr/remix/blob/fix-create-remix-params-demo-error-messages/docs/pages/contributing.md) and the [contributors.yml](https://github.com/thomasmarr/remix/blob/fix-create-remix-params-demo-error-messages/contributors.yml)

**Comment by ryanflorence** [comment]
Can you please make your changes on top of the `dev` branch?

**Comment by thomasmarr** [comment]
Yes, now that I have seen the contirbuting guide - I'll do that.

**Comment by thomasmarr** [comment]
Closing as these files appear to have been removed now.

**Pull request closed without merging**
