### PR TITLE
feat(remix-dev,remix-serve): Allow specifying HOST environment variable

### PR DESCRIPTION
**Pull request by rossipedia**
This will allow users to bind `remix-serve` to a specific interface, if they want to keep it private for example.

### CODE REVIEW

**Comment by mcansh** [comment]
can we bring this same change over to `remix dev`? https://github.com/remix-run/remix/blob/5acfa8519f93b13d166749e0a5fb9cbda4cd76fe/packages/remix-dev/cli/commands.ts#L269-L281

**Comment by rossipedia** [comment]
@mcansh yeah just added :+1:

**Comment by mcansh** [comment]
> @mcansh yeah just added 👍

perfect! i think this also covers the last bit from https://github.com/remix-run/remix/issues/1831#issuecomment-1075425553 so we can restrict to localhost only, right? `HOST=localhost remix dev`

**Comment by rossipedia** [comment]
The `express` types are particular about overloads. While it will work if you call `.listen(port, undefined, onListen)`, the typings complain because the overload that takes those 3 arguments requires that the second is a `string`, not a `string | undefined`. It also wants the first arg to be a `number`, instead of `string | number`, hence the `parseInt` stuff.

**Comment by rossipedia** [comment]
@mcansh gentle ping :)

**Comment by mcansh** [comment]
one more thing, can you switch this to point to dev?

**Pull request merged**
