### PR TITLE
fix(remix-eslint-config): add required @babel/core

### LINKED ISSUE #1179: [Bug]: missing @babel/core in remix-eslint-config
### Which Remix packages are impacted?

- [ ] `remix` (Remix core)
- [ ] `create-remix`
- [ ] `@remix-run/architect`
- [ ] `@remix-run/cloudflare-workers`
- [ ] `@remix-run/dev`
- [ ] `@remix-run/express`
- [ ] `@remix-run/netlify`
- [ ] `@remix-run/node`
- [ ] `@remix-run/react`
- [ ] `@remix-run/serve`
- [ ] `@remix-run/server-runtime`
- [ ] `@remix-run/vercel`

### What version of Remix are you using?

1.1.0

### What version of Node are you using? Minimum supported version is 14.

14.16.0

### Steps to Reproduce

1. access https://stackblitz.com/edit/github-1ywvff?file=package.json
2. run `npm run eslint`

### Expected Behavior

Eslint will run correctly

### Actual Behavior

```
Error: Failed to load parser '@babel/eslint-parser' declared in '.eslintrc » @remix-run/eslint-config': Cannot find module '@babel/core/package.json'
```

### PR DESCRIPTION
**Pull request by luffy84217**
Fix #1179

### CODE REVIEW

**Comment by MichaelDeBoey** [comment]
Duplicate of #1180

**Comment by luffy84217** [comment]
@MichaelDeBoey Sorry, I left comment to ask if someone is working on it on #1179 , and no one responded then, so I supposed it's up for grabs then. Not intentionally duplicate.

**Comment by MichaelDeBoey** [comment]
@luffy84217 No problem, those things happen 🤷‍♂️

**Comment by MichaelDeBoey** [comment]
@luffy84217 I think we can close this one, since we have #1180

**Pull request closed without merging**
