### PR TITLE
fix(v2_meta): hint data as being potentially undefined

### PR DESCRIPTION
**Pull request by machour**
I've been bitten by this in production a while ago, so here's my attempt at fixing it.

Not sure why we have duplicate types definitions in the react package, instead of a re-export from server-runtime.
Also, not sure this is the smartest fix, would definitely accept a better one

Closes: #6210 

- [ ] Docs
- [ ] Tests

Testing Strategy: 

<table>
<tr>
 <td>Before
 <td>After
<tr>
 <td>
Screenshot 2023-04-28 at 10 24 22 AM

 <td>
Screenshot 2023-04-28 at 10 24 01 AM

</table>

### CODE REVIEW

**Comment by aaronadamsCA** [comment]
Note this is a duplicate of #5787.

**Comment by machour** [comment]
Good catch @aaronadamsCA, thank you!

**Comment by machour** [comment]
Reopening for @brophdawg11 consideration.
I think that we both did half the job 😅

**Comment by brophdawg11** [comment]
yeah I like this one better too I think

**Pull request merged**
