### PR TITLE
test: windows testing updates

### PR DESCRIPTION
**Pull request by MichaelDeBoey**
Cherry-pick of #3915 against `dev`

### CODE REVIEW

**Review by mcansh — APPROVED** [review]

**Comment by mcansh** [comment]
these failing windows test make me nervous now lol, but i also have no idea if it's running whats on dev/main/or whats in this PR 😅

**Comment by kentcdodds** [comment]
Yeah, this didn't seem to make a difference :(

/me yells "Windows!" into the abyss while shaking my fists

**Comment by mcansh** [comment]
> Yeah, this didn't seem to make a difference :(
> 
> /me yells "Windows!" into the abyss while shaking my fists


haha, part of this appears that convert-to-javascript isn't working, running them locally on windows, i'm still left with ts files

**Comment by mcansh** [comment]
fix that issue here https://github.com/remix-run/remix/pull/3963

**Comment by MichaelDeBoey** [comment]
I really hate these failing Windows tests 😅

**Comment by mcansh** [comment]
ok, figured out the jest issues, due to node vm not supporting dynamic imports which jest uses 🥴 - once https://github.com/remix-run/remix/pull/3963 is merged, this should be good to go as well :)

**Review by chaance — APPROVED** [review]

**Pull request merged**
