### PR TITLE
ci(deployments): define required secrets

### PR DESCRIPTION
**Pull request by mcansh**
https://github.com/remix-run/remix/actions/runs/2513898715

Signed-off-by: Logan McAnsh <logan@mcan.sh>

Closes: #

- [ ] Docs
- [ ] Tests

Testing Strategy:

### CODE REVIEW

**Comment by MichaelDeBoey** [comment]
@mcansh I think this PR causes an error on all forks that don't have these secrets set 🤔
https://github.com/MichaelDeBoey/remix/actions/runs/2523109212

**Comment by mcansh** [comment]
> @mcansh I think this PR causes an error on all forks that don't have these secrets set 🤔
> 
> https://github.com/MichaelDeBoey/remix/actions/runs/2523109212

hm, i'd expect the "if" statement to make that not matter, we can change them to not required

**Comment by MichaelDeBoey** [comment]
> i'd expect the "if" statement to make that not matter

Each step will probably be skipped, but the workflow itself will already error out because they're all required inputs

**Comment by mcansh** [comment]
this is related to a misconfiguration im pretty sure - fixed here https://github.com/remix-run/remix/pull/3520

**Pull request merged**
