### PR TITLE
fix(remix-dev): update `xdm` dependency to allow disabling `skipLibCheck` when used on Cloudflare

### PR DESCRIPTION
**Pull request by fern64**
This pull request updates xdm to `3.4.0` which fixes https://github.com/wooorm/xdm/issues/109 which is relevant to all Remix apps on Cloudflare Pages written in TypeScript. By merging this PR, these developers are allowed to disable `skipLibCheck` in their `tsconfig.json` which results in additional type safety.

### CODE REVIEW

**Review by 3imed-jaberi — APPROVED** [review]
sgtm

**Comment by jensmeindertsma** [comment]
For clarification, this is the error message fixed by this pull request: https://github.com/jensmeindertsma/jensmeindertsma.com/runs/5345080983?check_suite_focus=true

**Comment by jensmeindertsma** [comment]
I'm updating this branch tomorrow, is there anything else I need to do to get this merged?

**Comment by machour** [comment]
That should be it @jensmeindertsma when conflicts are fixed.
We'll run actions on this PR, and if tests passes, someone from the team will give it a look as soon as the schedule permits.

**Comment by MichaelDeBoey** [comment]
@jensmeindertsma Could you please rebase your branch onto latest `dev` & fix conflicts?

**Pull request closed without merging**
