### PR TITLE
fix(templates/cloudflare-pages,cloudflare-workers): update required `node` version

### PR DESCRIPTION
**Pull request by zhe**
"cloudflare-pages" template uses wrangler2 (`beta` at this moment) which requires `node` version at least `16.7.0`, see: https://github.com/cloudflare/wrangler2/pull/271, https://github.com/remix-run/remix/pull/1391 or https://github.com/cloudflare/wrangler2/blob/575962d2f1c59aa07ac7398500e8cc7e0fde9e7f/package.json#L43 

If using node 14, the `dev` script may fail.

Thinking it might be nice to specify node version in the `package.json` `engines` to give users a possible friendly message in the terminal, especially using `yarn` or `pnpm`

```
error remix-app-template@: The engine "node" is incompatible with this module. Expected version ">=16.7.0". Got "14.17.6"
```

```
 WARN  Unsupported engine: wanted: {"node":">=16.7.0"} (current: {"node":"v14.17.6","pnpm":"6.31.0"})
```

This PR replaces an old one: #2026

### CODE REVIEW

**Review by sergiodxa — APPROVED** [review]

**Comment by MichaelDeBoey** [comment]
Let's wait for this to merge until we have a new release and #2317 is available in `main`

**Comment by zhe** [comment]
Just updated this PR. Noticed latest cloudflare-pages template showed some warnings when installing dependencies: it seems `warangler` v2's deps require node version `>=16.13` now.

```bash
❯ npm install
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@miniflare/cache@2.7.1',
npm WARN EBADENGINE   required: { node: '>=16.13' },
npm WARN EBADENGINE   current: { node: 'v16.7.0', npm: '7.20.3' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@miniflare/cli-parser@2.7.1',
npm WARN EBADENGINE   required: { node: '>=16.13' },
npm WARN EBADENGINE   current: { node: 'v16.7.0', npm: '7.20.3' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@miniflare/core@2.7.1',
npm WARN EBADENGINE   required: { node: '>=16.13' },
npm WARN EBADENGINE   current: { node: 'v16.7.0', npm: '7.20.3' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@miniflare/durable-objects@2.7.1',
npm WARN EBADENGINE   required: { node: '>=16.13' },
npm WARN EBADENGINE   current: { node: 'v16.7.0', npm: '7.20.3' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@miniflare/html-rewriter@2.7.1',
npm WARN EBADENGINE   required: { node: '>=16.13' },
npm WARN EBADENGINE   current: { node: 'v16.7.0', npm: '7.20.3' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@miniflare/http-server@2.7.1',
npm WARN EBADENGINE   required: { node: '>=16.13' },
npm WARN EBADENGINE   current: { node: 'v16.7.0', npm: '7.20.3' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@miniflare/kv@2.7.1',
npm WARN EBADENGINE   required: { node: '>=16.13' },
npm WARN EBADENGINE   current: { node: 'v16.7.0', npm: '7.20.3' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@miniflare/r2@2.7.1',
npm WARN EBADENGINE   required: { node: '>=16.13' },
npm WARN EBADENGINE   current: { node: 'v16.7.0', npm: '7.20.3' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@miniflare/runner-vm@2.7.1',
npm WARN EBADENGINE   required: { node: '>=16.13' },
npm WARN EBADENGINE   current: { node: 'v16.7.0', npm: '7.20.3' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@miniflare/scheduler@2.7.1',
npm WARN EBADENGINE   required: { node: '>=16.13' },
npm WARN EBADENGINE   current: { node: 'v16.7.0', npm: '7.20.3' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@miniflare/shared@2.7.1',
npm WARN EBADENGINE   required: { node: '>=16.13' },
npm WARN EBADENGINE   current: { node: 'v16.7.0', npm: '7.20.3' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@miniflare/sites@2.7.1',
npm WARN EBADENGINE   required: { node: '>=16.13' },
npm WARN EBADENGINE   current: { node: 'v16.7.0', npm: '7.20.3' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@miniflare/storage-file@2.7.1',
npm WARN EBADENGINE   required: { node: '>=16.13' },
npm WARN EBADENGINE   current: { node: 'v16.7.0', npm: '7.20.3' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@miniflare/storage-memory@2.7.1',
npm WARN EBADENGINE   required: { node: '>=16.13' },
npm WARN EBADENGINE   current: { node: 'v16.7.0', npm: '7.20.3' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@miniflare/watcher@2.7.1',
npm WARN EBADENGINE   required: { node: '>=16.13' },
npm WARN EBADENGINE   current: { node: 'v16.7.0', npm: '7.20.3' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@miniflare/web-sockets@2.7.1',
npm WARN EBADENGINE   required: { node: '>=16.13' },
npm WARN EBADENGINE   current: { node: 'v16.7.0', npm: '7.20.3' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'miniflare@2.7.1',
npm WARN EBADENGINE   required: { node: '>=16.13' },
npm WARN EBADENGINE   current: { node: 'v16.7.0', npm: '7.20.3' }
npm WARN EBADENGINE }
```

**Review by MichaelDeBoey — APPROVED** [review]

**Comment by MichaelDeBoey** [comment]
@zhe Since we're using `wrangler` in the `cloudflare-workers` template as well (see #3160), do we want to do this change in that template as well?

CC/ @jacob-ebey

**Comment by zhe** [comment]
@MichaelDeBoey thanks for the feedback. Some warnings also showed up after running `npm install` in a fresh `cloudflare-workers` template, it's probably a good time to update that too?

node 14.19.0
```base
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN notsup Unsupported engine for miniflare@2.7.1: wanted: {"node":">=16.13"} (current: {"node":"14.19.0","npm":"6.14.16"})
npm WARN notsup Not compatible with your version of node/npm: miniflare@2.7.1
npm WARN notsup Unsupported engine for wrangler@2.0.27: wanted: {"node":">=16.7.0"} (current: {"node":"14.19.0","npm":"6.14.16"})
npm WARN notsup Not compatible with your version of node/npm: wrangler@2.0.27
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: esbuild-android-arm64@0.14.22 (node_modules/esbuild/node_modules/esbuild-android-arm64):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for esbuild-android-arm64@0.14.22: wanted {"os":"android","arch":"arm64"} (current: {"os":"darwin","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: esbuild-freebsd-64@0.14.22 (node_modules/esbuild/node_modules/esbuild-freebsd-64):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for esbuild-freebsd-64@0.14.22: wanted {"os":"freebsd","arch":"x64"} (current: {"os":"darwin","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: esbuild-darwin-arm64@0.14.22 (node_modules/esbuild/node_modules/esbuild-darwin-arm64):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for esbuild-darwin-arm64@0.14.22: wanted {"os":"darwin","arch":"arm64"} (current: {"os":"darwin","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: esbuild-freebsd-arm64@0.14.22 (node_modules/esbuild/node_modules/esbuild-freebsd-arm64):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for esbuild-freebsd-arm64@0.14.22: wanted {"os":"freebsd","arch":"arm64"} (current: {"os":"darwin","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: esbuild-linux-32@0.14.22 (node_modules/esbuild/node_modules/esbuild-linux-32):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for esbuild-linux-32@0.14.22: wanted {"os":"linux","arch":"ia32"} (current: {"os":"darwin","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: esbuild-linux-arm@0.14.22 (node_modules/esbuild/node_modules/esbuild-linux-arm):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for esbuild-linux-arm@0.14.22: wanted {"os":"linux","arch":"arm"} (current: {"os":"darwin","arch":"x64"})
...
```

node 16.7.0
```bash
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@miniflare/cache@2.7.1',
npm WARN EBADENGINE   required: { node: '>=16.13' },
npm WARN EBADENGINE   current: { node: 'v16.7.0', npm: '7.20.3' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@miniflare/cli-parser@2.7.1',
npm WARN EBADENGINE   required: { node: '>=16.13' },
npm WARN EBADENGINE   current: { node: 'v16.7.0', npm: '7.20.3' }
npm WARN EBADENGINE }
...
```

**Comment by MichaelDeBoey** [comment]
@zhe That's indeed what I was referring to with my latest comment, that we should probably update `cloudflare-workers` template as well, since we're now using `wrangler` too as of #3160 👍

**Comment by zhe** [comment]
@MichaelDeBoey thank you for the feedback. `cloudflare-workers` template has been updated as well. Kindly review.

**Review by mcansh — APPROVED** [review]

**Review by MichaelDeBoey — APPROVED** [review]

**Pull request merged**
