### PR TITLE
chore(remix-dev): update `proxy-agent` dependency

### LINKED ISSUE #6833: @remix-run/dev critical security vulnerabilities from dependencies
### What version of Remix are you using?

1.18.1

### Are all your remix dependencies & dev-dependencies using the same version?

- [X] Yes

### Steps to Reproduce

Install all remix packages 1.18.1.
Run `npm audit`.

### Expected Behavior

Should be 0 critical vulnerabilities. 

### Actual Behavior

`npm audit` outputs the following:
```sh
vm2  *
Severity: critical
vm2 Sandbox Escape vulnerability - https://github.com/advisories/GHSA-cchq-frgv-rjh5
fix available via `npm audit fix --force`
Will install @remix-run/dev@1.7.2, which is a breaking change
node_modules/vm2
  degenerator  >=3.0.0
  Depends on vulnerable versions of vm2
  node_modules/degenerator
    pac-resolver  >=5.0.0
    Depends on vulnerable versions of degenerator
    node_modules/pac-resolver
      pac-proxy-agent  >=5.0.0
      Depends on vulnerable versions of pac-resolver
      node_modules/pac-proxy-agent
        proxy-agent  >=5.0.0
        Depends on vulnerable versions of pac-proxy-agent
        node_modules/proxy-agent
          @remix-run/dev  <=0.0.0-nightly-ff40409-20230514 || >=1.7.3-pre.0
          Depends on vulnerable versions of proxy-agent
          node_modules/@remix-run/dev

word-wrap  *
Severity: moderate
word-wrap vulnerable to Regular Expression Denial of Service - https://github.com/advisories/GHSA-j8xg-fqg3-53r7
fix available via `npm audit fix`
node_modules/word-wrap
  optionator  0.8.3 - 0.9.1
  Depends on vulnerable versions of word-wrap
  node_modules/escodegen/node_modules/optionator
  ```

As an extra, the moderate vulnerability with word-wrap seems to be a dependency of escodegen, which is a dependency of degenerator - so I'm assuming that's coming from the same chain of dependencies from `@remix-run/dev 1.18.1` 

I'm guessing this is already known & obvious - but can't see any issues reported in relation to it, or anything on the discord. Don't know if these security vulnerabilities are worth creating an issue for or not.

### PR DESCRIPTION
**Pull request by roughee**
Fixes #6833

### CODE REVIEW

**Comment by rickbatka** [comment]
Any maintainers want to weigh in on this? `npm audit` is now reporting critical vulnerabilities for everyone using Remix.

FWIW, I tried using a "resolutions" override in my Remix app to force proxy-agent to 6.3.0, and it breaks `remix build`:
```
  "resolutions": {
    "proxy-agent" : "^6.3.0",
}
```

Then ran:
```
yarn install
yarn build
```
Here is the output from `remix build`:

```
/workspaces/platform/web/node_modules/@remix-run/dev/dist/cli/create.js:67
const defaultAgent = new ProxyAgent__default["default"]();
                     ^

TypeError: ProxyAgent__default.default is not a constructor
    at Object.<anonymous> (/workspaces/platform/web/node_modules/@remix-run/dev/dist/cli/create.js:67:22)
    at Module._compile (node:internal/modules/cjs/loader:1255:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1309:10)
    at Module.load (node:internal/modules/cjs/loader:1113:32)
    at Module._load (node:internal/modules/cjs/loader:960:12)
    at Module.require (node:internal/modules/cjs/loader:1137:19)
    at require (node:internal/modules/helpers:121:18)
    at Object.<anonymous> (/workspaces/platform/web/node_modules/@remix-run/dev/dist/cli/commands.js:56:16)
    at Module._compile (node:internal/modules/cjs/loader:1255:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1309:10)
    at Module.load (node:internal/modules/cjs/loader:1113:32)
    at Module._load (node:internal/modules/cjs/loader:960:12)
    at Module.require (node:internal/modules/cjs/loader:1137:19)
    at require (node:internal/modules/helpers:121:18)
    at Object.<anonymous> (/workspaces/platform/web/node_modules/@remix-run/dev/dist/cli/run.js:22:16)
    at Module._compile (node:internal/modules/cjs/loader:1255:14)

Node.js v20.2.0
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

Rebuilding...
ERROR: "dev:remix" exited with 1.
error Command failed with exit code 1.
```

I worry that this PR might not go far enough to fix the issue - it might clear the vulnerability warning, while also breaking the remix compiler.

But I'm just taking a guess.

**Comment by roughee** [comment]
@rickbatka 

you are welcome to try yourself on the remix repo it builds just fine.

`git checkout dev`
`yarn install`
`npx playwright install`
`yarn build`
`yarn test`

image

then

`cd packages`
`cd remix-dev`
`yarn upgrade proxy-agent@^6.3.0`
`cd ..`
`cd ..`
`yarn install`
`yarn build`
`yarn test`

image

**Review by MichaelDeBoey — APPROVED** [review]

**Review by pcattori — APPROVED** [review]

**Comment by averypelle** [comment]
I would advocate in favor of a patch release containing just this change. If the larger PR is part of a breaking change, many codebases will be exposed to this vulnerability for a much longer time - i.e. until they migrate to the latest version. Importantly, `vercel` remains vulnerable via its dependency on this project https://github.com/vercel/vercel/issues/10222 . A patch version would allow for a much quicker resolution for that repo and the many codebases that use it.

**Comment by rickbatka** [comment]
> @machour @brophdawg11 I would advocate in favor of a patch release containing just this change.
> 
> If the larger PR is part of a breaking change, many codebases will be exposed to this vulnerability for a much longer time, i.e. until they figure out how to migrate to the latest major version.
> 
> Importantly, `vercel` remains exposed to this critical security vulnerability via its dependency on this project [vercel/vercel#10222](https://github.com/vercel/vercel/issues/10222) . A patch version would allow for a much quicker resolution for that repo and the many codebases that use it.

I agree, my codebase is one of those affected (we are on 1.18). This really should go out as a patch release for all supported versions of Remix. The vulnerability is quite serious (maintainer pulled his package and made various statements online).

**Comment by quinn** [comment]
I think this is an appropriate patch release on the 1.19 series given the critical vulnerability. I'd like to get this updated and clear my security alerts :)

**Comment by brophdawg11** [comment]
We've got another fix we'd like to put out in a `1.19.2` so I cherry-picked these into https://github.com/remix-run/remix/pull/7027 to include as well

**Comment by brophdawg11** [comment]
Also cross-posting [this comment](https://github.com/remix-run/remix/issues/6833#issuecomment-1644258808) for visibility.  This is _not_ a vulnerability with your runtime app.  This is something only used by the `create-remix` CLI tool, which is currently part of `@remix-run/dev` which is why you're seeing the npm warning.  Your production application is not using the `create-remix` CLI, and thus is not impacted.  It's just a symptom of the design of `npm audit` ([tl;dr;](https://overreacted.io/npm-audit-broken-by-design/))

**Pull request closed without merging**
