### PR TITLE
tests(remix-react): add tests for `ScrollRestoration` component

### PR DESCRIPTION
**Pull request by hjonasson**
There was a test in `scroll-restoration-test.tsx` with a `it.todo` and I wanted to have a go at it.

I added two tests. 
- One is for a component with a scroll state set on a previous render.
- Another one for a back-and-forth navigation that preserves scrolling.

I had previously created another PR [here](https://github.com/remix-run/remix/pull/5417) where I wanted to learn about the PR process. If my branching is all messed up let me know and I will fix it.

### CODE REVIEW

**Comment by hjonasson** [comment]
Is there somebody I can ping for a review?

**Review by machour — DISMISSED** [review]
hey @hjonasson, and thank you for taking this initiative, really appreciate the spirit here 🙏🏼 

could you target `dev` instead of `main` ?
we only use main for PR touching documentation or our templates (see the [Branches](https://github.com/remix-run/remix/blob/main/docs/pages/contributing.md#branches) section of the contributing guide)

**Comment by hjonasson** [comment]
thanks @machour ! I saw the docs but I had forked from main...I was not quite sure. Let me fix it up and tag you again 😄

**Comment by hjonasson** [comment]
@machour a friendly ping :D

**Comment by hjonasson** [comment]
Thanks @MichaelDeBoey !

**Review by brophdawg11 — APPROVED** [review]

**Comment by brophdawg11** [comment]
Thanks @hjonasson!

**Pull request merged**
