### PR TITLE
fix(docs,examples,templates): make `npm-run-all` calls work when using Yarn

### PR DESCRIPTION
**Pull request by lensbart**
`run-p dev:*` [doesn’t](https://github.com/mysticatea/npm-run-all/issues/196) (but probably should) work with Yarn. Thankfully, this can be fixed [quite easily](https://github.com/mysticatea/npm-run-all/issues/196#issuecomment-893470240) by wrapping the argument in quotes.

(As an aside, I find single quotes a bit cleaner than escaped double quotes, but I saw that escaped quotes were already used elsewhere so I stuck to the convention.)

### CODE REVIEW

**Review by MichaelDeBoey — CHANGES_REQUESTED** [review]
We already had #2417 to start working on this.
Since it didn't get any response in the last 25 days, I'd rather get this one merged instead.

1 thing I want to do here too though is also update all `run-s` calls as well.

I also prefer using single quotes tbh, as that makes it a bit more easy on the eyes (and has a lower cognitive load as well, since you don't need to think about where you are in the script & if you have escaped all of the correctly)

**Comment by lensbart** [comment]
@MichaelDeBoey consider it done!

**Review by MichaelDeBoey — APPROVED** [review]

**Review by kentcdodds — CHANGES_REQUESTED** [review]
I'm pretty sure single quotes make this not work on windows. I've never heard of needing to quote these npm-run-all usages for Windows support 🤔

**Comment by lensbart** [comment]
@kentcdodds fixed

**Review by MichaelDeBoey — APPROVED** [review]

**Review by kentcdodds — APPROVED** [review]
Thanks!

**Pull request merged**
