### PR TITLE
feat(remix-dev): add `providerImportSource` to `xdm` compile step

### PR DESCRIPTION
**Pull request by joshuaellis**
Relates to: #2907 

- [ ] Docs
- [ ] ~Tests~

Testing Strategy: I couldn't see any tests specifically around MDX so have not added a new one, if there's something i've missed then please, let me know and I will amend.

### CODE REVIEW

**Comment by joshuaellis** [comment]
RE. Docs, I was thinking of adding some to `mdx#Advanced-Configuration` regarding this to match where you've highlighted adding your own remark / rehype plugins.

**Comment by joshuaellis** [comment]
Hey @MichaelDeBoey this PR is really important for `react-spring`'s doc site because Vercel now patch `@remix-run/dev` so I'm struggling to manage updating remix / keeping up to date with vercel etc.

Is there an estimation on when this PR might be merged or discussed further? I know there's also MDX 2 which is recommended over XDM but I also believe that would be a breaking change so this feature might be good in the interim...?

**Comment by MichaelDeBoey** [comment]
Hi @joshuaellis!

Are you still interested in getting this one merged?

If so, please rebase onto latest `dev` & resolve conflicts

**Comment by ryanflorence** [comment]
With the forthcoming vite compiler, apps have complete control over how they want to handle non-javascript imports like MDX.

https://remix.run/docs/en/main/future/vite#add-mdx-plugin

Thanks for the PR @joshuaellis, sorry it didn't get our attention, we've been trying to get out of the compiler game, but should have at least told you that a long time ago 😅

**Comment by joshuaellis** [comment]
Better to reply at some time rather than never! Thank you regardless 🤩

**Pull request closed without merging**
