### PR TITLE
Fixes Blog.md React App Server -> Remix App Server

### PR DESCRIPTION
**Pull request by filipbarak**
You probably meant Remix App Server since there is not React App Server in the list of options.

### CODE REVIEW

**Comment by Dandan821** [comment]
https://vuuzletvph.com/heads-up-vuco-bounty-programs-are-coming-your-way/

**Comment by Dandan821** [comment]
https://vuuzletvph.com/heads-up-vuco-bounty-programs-are-coming-your-way/

**Review by MichaelDeBoey — APPROVED** [review]

**Comment by MichaelDeBoey** [comment]
This is already fixed in 20997dd1d56722abcfdb6e37e59fc21db8e72a48

**Comment by ryanflorence** [comment]
Thank you for your help, but it looks like we've already fixed this.

If I'm wrong, please re-open this issue and we'll get it sorted out. Thanks!

**Pull request closed without merging**
