### PR TITLE
feat(remix-dev): add `.node` file support for Node based platforms

### PR DESCRIPTION
**Pull request by benwis**
## Changes Made
This pull requests adds an esbuild plugin and some tweaks to the Remix compiler to allow the import of `.node` files in Remix's loaders and actions. While I was motivated by the desire to write Rust helper functions for server side modules, this was also mentioned in this [other pull request](https://github.com/remix-run/remix/pull/703) for .node imports for remix-tailwind, and in [a discussion](https://github.com/remix-run/remix/discussions/2560) by @nicksrandall for sharp support.

I have started [a discussion](https://github.com/remix-run/remix/discussions/3201) here, but as of now hasn't generated much traffic.

## Benefits
The primary benefit I see is the ability to run other language's code on your server easily in Remix. This could be done in Rust using napi-rs, in Python, or in C. That offers substantial benefits in performance, opens possibilities for easy concurrency, and other possibilities.

## Limitations
One of the biggest limitations is that it can only run on Node based platforms. Napi-rs is currently working on Deno support, so we may see this come there as well. 

## Testing
I have modified the Rust example in the main repo with to generate a sum() function with [napi-rs](https://napi.rs/) and use that to perform the addition that example does. The repo for this is [here](https://github.com/benwis/rust-remix). There are a few build steps as described in that README that must be performed, depending on the platform you're running Remix on.

- [x] Docs

### CODE REVIEW

**Comment by nicksrandall** [comment]
I've run into this issue, thanks for adding support! I started a disucsion about this awhile but no body ever commented. Hopefully you get more traction! 

https://github.com/remix-run/remix/discussions/2560

**Comment by benwis** [comment]
> I've run into this issue, thanks for adding support! I started a disucsion about this awhile but no body ever commented. Hopefully you get more traction!
> 
> #2560

I hadn't seen your discussion before, I suspect the reason it didn't get much traction is that it's a somewhat niche feature. Perhaps after Remix Conf we'll get a bit more interest, but I'm fairly confident I can get this merged after I write some docs and do some celeanup

**Comment by MichaelDeBoey** [comment]
@benwis Code changes should go against `dev`.
Can you please rebase your branch onto `dev` & set the base branch to `dev` as well?

**Comment by benwis** [comment]
Closing this so that I can pull from my fork's dev branch against the remix dev branch. New PR [here](https://github.com/remix-run/remix/pull/3261):

**Pull request closed without merging**
