### PR TITLE
feat(remix-dev): upgrade `unstable_cssModules` config option to `v2_cssModules`

### PR DESCRIPTION
**Pull request by MichaelDeBoey**
Follow-up of @markdalgleish's #5800

### CODE REVIEW

**Comment by markdalgleish** [comment]
I'm not sure if we want to introduce churn around this flag just before v2. Do you mind if we close this for now and potentially come back to it?

**Comment by MichaelDeBoey** [comment]
@markdalgleish As pointed out in @brophdawg11's #5829, the way to go is to upgrade `unstable_*` flags to `v2_*` once the API is becoming stable, so that's why I created this PR

**Comment by chaance** [comment]
> @markdalgleish As pointed out in @brophdawg11's #5829, the way to go is to upgrade `unstable_*` flags to `v2_*` once the API is becoming stable, so that's why I created this PR

This is generally the idea, but I think with the CSS stuff it might not be worth bumping to `v2_` for brand new features that don't break or impact current APIs. Matt's comment was more about how we approach new major-version changes to APIs in the future. New experimental/unstable features can stabilize at any point and be merged before a major release so long as nothing is breaking!

**Comment by MichaelDeBoey** [comment]
So basically `unstable_cssModules` should actually be released in `dev` instead of `v2` in future scenarios, but for this time the team opted to do it in `v2`?

**Pull request closed without merging**
