### PR TITLE
docs(templates/express): fix `README`

### PR DESCRIPTION
**Pull request by dogukanakkaya**
Express Server build path is not in the server dir. It is in the root dir of the project.

### CODE REVIEW

**Comment by MichaelDeBoey** [comment]
@dogukanakkaya Changes to `templates` go on `main` branch.
Could you please rebase your branch latest `main`?

**Comment by dogukanakkaya** [comment]
@MichaelDeBoey done.

**Comment by MichaelDeBoey** [comment]
Let's wait for this to merge until we have a new release and #2317 is available in `main`

**Comment by MichaelDeBoey** [comment]
@dogukanakkaya Please rebase your branch onto latest `main` & fix conflicts

**Pull request merged**
